### ISSUE TITLE
Clean doc from old-type playground url

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#1058]
In reference of this [forum topic](http://www.html5gamedevs.com/topic/38155-problem-with-playground-example-in-how-to/), we have to clean up and update some playground links/examples.

Here the result of a search on Atom with the old pattern url:

![old pattern](https://i.imgur.com/tKAT7ol.png)

**Comment by deltakosh** [comment]
Good catch!

**Comment by deltakosh** [comment]
Fixed!

**Comment by Vinc3r** [comment]
GG :)
