### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by GrosSacASac** [BabylonJS/OldDocumentationSite#108]
http://doc.babylonjs.com/classes/2.3/BaseTexture#new-basetexture-classes-2-3-basetexture-scene-

the tutorial link is a link that returns a 404 error

**Comment by RaananW** [comment]
works here, could you check again?
maybe it was temporarily down, or the website was rebuilt.

**Comment by GrosSacASac** [comment]
checked again still 404 (this link http://doc.babylonjs.com/tutorials/04._Materials)
also at

http://doc.babylonjs.com/classes/2.3/StandardMaterial#new-standardmaterial-classes-2-3-standardmaterial-name-scene-

broken http://babylondoc.azurewebsites.net/page.php?p=24706

**Comment by RaananW** [comment]
Not sure where you get those links from (if they are linked internally, please let us know).
The 2nd link works. I don't get a 404. Same as the link from the original post. The Materials link is old, and the last link is a link to the old doc website, that no longer exists.
If those are links from the forum, there is sadly very little we can do about it. If they are linked internally in the doc page, we will repair them asap.

**Comment by RaananW** [comment]
Ok, found the wrong places. It is all based on old code documentation. if you want to submit a PR correcting it, please do. If not, we will repair it soon.
Thanks!
