### ISSUE TITLE
Show distinction between inherited / new properties and methods

### ISSUE THREAD

**Issue by bartwttewaall** [BabylonJS/OldDocumentationSite#1086]
Please generate the api documentation with clear visual distinction between inherited vs new properties and methods. Example: https://createjs.com/docs/easeljs/classes/Container.html
This makes it more usable when trying to figure out which base class to extend from.

**Comment by deltakosh** [comment]
We are using Typedoc for Doc generation. Need to check if this option is supported

**Comment by deltakosh** [comment]
That's the best we can get so far:
![image](https://user-images.githubusercontent.com/1306056/41750068-c40ee20e-756e-11e8-9e33-39bae2cf15fe.png)

**Comment by deltakosh** [comment]
Will reopen if typedoc offer other alternatives (Or if someone knows how to do it better :))

**Comment by deltakosh** [comment]
You also have this info here:
![image](https://user-images.githubusercontent.com/1306056/41750117-fdf73430-756e-11e8-9b3f-891e322237a3.png)
