### ISSUE TITLE
Babylonjs Documentation main page search bar susceptible to cross-site scripting

### ISSUE THREAD

**Issue by BradShepps** [BabylonJS/OldDocumentationSite#1133]
Javascript can be written and executed in the search bar on main documentation page.

**Comment by deltakosh** [comment]
What is your suggestion to fix it?

**Comment by deltakosh** [comment]
Pinging @Jaskar

**Comment by Jaskar** [comment]
Thanks for the reporting @BradShepps .
I'll fix it today !

**Comment by deltakosh** [comment]
Today? :)

**Comment by sebavan** [comment]
@Jaskar any update ?

**Comment by Jaskar** [comment]
My bad! I forgot before going to holidays. I'm correcting that today (for real this time).

**Comment by Jaskar** [comment]
Temp fix : https://github.com/BabylonJS/Documentation/pull/1202

**Comment by Jaskar** [comment]
Final fix waiting for PR !

**Comment by sebavan** [comment]
THANKS
