### ISSUE TITLE
How to save the simplified results after Auto-LOD?

### ISSUE THREAD

**Issue by yzthr** [BabylonJS/OldDocumentationSite#1143]
Hello,
I find that simplifying a complex mesh may take a lot of time, as in demo: https://www.babylonjs-playground.com/#2JBSNA#3 , it will take about 10s for the pop-up alert window. So how do i save the meshes after the Auto-LOD simplify, so i can load the simplified meshes in the next time(it will save a lot of time)?(I can't find the approach in this doc)   Thanks!

**Comment by RaananW** [comment]
Hi!

The simplification process was meant to work in real-time. There are better (and slower, one must say) simplification processes out there if you want to serve different simplified versions of your mesh.
Having said that - you have access to all LOD levels. For example:

https://www.babylonjs-playground.com/#2JBSNA#42
