### ISSUE TITLE
Ability to download a local browsable copy of the API

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#1189]
As seen on [this forum thread](http://www.html5gamedevs.com/topic/39280-improving-api-browsing/?do=findComment&comment=224601), it could be interesting to save and keep a local version of the API.

As example, you can check the [Blender Python API](https://docs.blender.org/api/blender_python_api_current/):
![img](https://i.imgur.com/PuBLrPj.png)

**Comment by sebavan** [comment]
Yup, let s see how to add this. If somebody wants to give it a shot ?

**Comment by deltakosh** [comment]
The missing piece will be search :( And you can still download the repo and use it locally
