### ISSUE TITLE
Add glTF extension support feature list to 3dsmax, maya and gltf serializer  

### ISSUE THREAD

**Issue by sbtron** [BabylonJS/OldDocumentationSite#1296]
Docs need to be updated to reflect latest capabilities and can have a summary table that follow the pattern form here - https://github.com/KhronosGroup/glTF/issues/1271#issuecomment-371204827

**Comment by sbtron** [comment]
@Drigax do you have an overview of current exporter support?

**Comment by deltakosh** [comment]
Up @Drigax

**Comment by thomlucc** [comment]
Issue moved to [BabylonJS/Documentation #160](https://github.com/BabylonJS/Documentation/issues/160) via [**ZenHub**](https://www.zenhub.com/)
