### ISSUE TITLE
[suggestion] new How To category: PBR

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#1300]
for now we have *Start with Physically Based Rendering (PBR)* and *Master Physically Based Rendering* in category *Environment*.

What do you think to put these pages in a dedicated category named *PBR*?

**Comment by deltakosh** [comment]
Agree!! Please add it if you are ok. This is a good idea

**Comment by Vinc3r** [comment]
ok, will do that in the few hours coming :)

**Comment by Vinc3r** [comment]
job done
