### ISSUE TITLE
enhancement: be able to get anchor in Examples page

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#1353]
Should be nice to share a link of https://doc.babylonjs.com/examples/ allowing the load of a specific scene

Examples : https://doc.babylonjs.com/examples/#colorCurves, https://doc.babylonjs.com/examples/#fresnel

I know we can send the playground link, but sharing the Example page on the forum could help to "promote" it, isn't it?

**Comment by deltakosh** [comment]
Yes but not supported for now and honestly the value added is not obvious

**Comment by Vinc3r** [comment]
ok, so forget about it ^^
