### ISSUE TITLE
dead cdn link in docs

### ISSUE THREAD

**Issue by roscopetracula** [BabylonJS/OldDocumentationSite#1368]
just FYI -- the docs at https://doc.babylonjs.com/how_to/using_the_physics_engine point at https://cdn.babylonjs.com/Ammo.js, but at the moment this link 404s. Thanks!

(also filed an issue at https://github.com/BabylonJS/CDN/issues/1 -- not sure if this is a docs or a cdn issus)

**Comment by deltakosh** [comment]
This will be the case when 4.0 will be out. In the meantime you can get it from preview.babylonjs.com
