### ISSUE TITLE
Title of every page is "Babylon.js Documentation"

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/OldDocumentationSite#1372]
Go to any page in the documentation. For example:
- https://doc.babylonjs.com/how_to/combine
- https://doc.babylonjs.com/how_to/group

Both of these titles are "Babylon.js Documentation". This causes not-so-great behavior when pasting link into the [forum](https://forum.babylonjs.com/t/optimised-scene-clones-or-one-big-mesh/660/6) where the link is displayed as "Babylon.js Documentation".

Can we update the title to be the actual title of the page?

**Comment by Vinc3r** [comment]
This will also helps in search engines. Google add I-don't-know-how the title of the pages, but not others:

![img](https://i.imgur.com/krvaVKU.png)

![img](https://i.imgur.com/0mNOcet.png)

![img](https://i.imgur.com/KqN6zht.png)

![img](https://i.imgur.com/P3PeuO9.png)
