### ISSUE TITLE
Folder devLocal not found

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#1410]
Not able to follow the advice below as I cannot find the devLocal folder in  BabylonJS/Babylon.js 

Does it exist? If so where do I find it? If not what should the advice read?

Local Dev with the Playground
A quick way to test if your code works is to open the local playground and write code that calls on the classes you have created.

It is also possible to copy and paste playgrounds code in the /devLocal/src/index.js file. The entire /devLocal/src folder is git ignored and is meant to be your local test folder.

You can launch it through: http://localhost:1338/localDev/index.html

**Comment by deltakosh** [comment]
This works for me. You must be in VScode, make sure to run npm install first in the tools/gulp folder and then hit f5 to start the debugging process

Pinging @sebavan  who is also doing the same but from the CLI

**Comment by BabylonJSGuide** [comment]
Where is the /devLocal/src/index.js folder? I cannot find it?

**Comment by deltakosh** [comment]
It is not part of the repo as everyone can create his own

**Comment by BabylonJSGuide** [comment]
OK worked it out the address is wrong - it should be localDev not devLocal. Will correct the docs.
