### ISSUE TITLE
Inconsitent versions in Typescript tutorial links

### ISSUE THREAD

**Issue by LunarLanding** [BabylonJS/OldDocumentationSite#1427]
Here: https://doc.babylonjs.com/

> you will need to download the BabylonJS TypeScript definition file from https://cdn.babylonjs.com/babylon.d.ts in 

Should link to the preview version, i.e. https://preview.babylonjs.com/babylon.d.ts , to be in accordance with the html snippet.

**Comment by deltakosh** [comment]
Good point! Let me fix that
