### ISSUE TITLE
Longer documentation main menu titles are truncated at desktop screen widths

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/OldDocumentationSite#1514]
For example "What's new" is truncated to "What's" and "Babylon 101" is truncated to "Babylon".

<img width="1410" alt="Screen Shot 2019-05-03 at 7 34 59 pm" src="https://user-images.githubusercontent.com/1428000/57129713-a3357b00-6dda-11e9-8354-e1460395c108.png">

Test in Chrome & Firefox at 100% zoom level on 13" MacBook Pro

**Comment by deltakosh** [comment]
Good catch!!

Need to find a smart way to fix that :D

**Comment by brian-hay** [comment]
I had a bit of a play with it locally. A quick interim fix would be to remove the fixed equal widths on the menu items, which I think looks better anyway, and possibly increase the breakpoint at which the mobile menu kicks in. The search box could also be reduced in size. The bigger problem though is that there's a lot of top-level menu items, too many I'd say. Probably what's really needed is a bit of an information architecture review and consolidating some menu items down to 6-8 at most. Just some thoughts.

Also the search box is not well integrated aesthetically. Suggest adding thick border of same color as header background deep purple so it looks like part of header.

I can have a go if you like.

**Comment by deltakosh** [comment]
Oh please do!

**Comment by brian-hay** [comment]
@deltakosh created PR.

A lot of the SASS was already there but had been overridden, so I mostly just cleaned up.

Still worth reviewing IA though at some point I think and mobile responsive header could do with a more comprehensive refactoring to further clean up and maybe bring it into closer alignment with the new BJS website design.

**Comment by deltakosh** [comment]
We plan to rework the design very soon to better align with the main website design

thanks a lot
