### ISSUE TITLE
How to use instances page has broken link

### ISSUE THREAD

**Issue by mthaddon** [BabylonJS/OldDocumentationSite#1521]
https://doc.babylonjs.com/how_to/how_to_use_instances has link that's no longer active. At the bottom of the page it includes a link to http://www.babylonjs.com/?INSTANCES but this isn't a link to demos of instances.

Fwiw, some external content (such as https://blog.raananweber.com/2015/09/03/scene-optimization-in-babylon-js/) also links to that URL, so might be worth fixing if possible, or if not, changing.

I'm happy to submit a PR if someone can let me know what this should be.

**Comment by deltakosh** [comment]
Will gladly merge the PR :)
Thanks a lot!

**Comment by mthaddon** [comment]
@deltakosh Do you know what the link should be updated to? I'm not sure what http://www.babylonjs.com/?INSTANCES used to point to.

**Comment by deltakosh** [comment]
I would say this one:
https://www.babylonjs-playground.com/#YB006J#0
