### ISSUE TITLE
Mixed content on https://doc.babylonjs.com/babylon101/lights and broken image

### ISSUE THREAD

**Issue by mthaddon** [BabylonJS/OldDocumentationSite#1550]
Hi,

There's a mixed content warning on https://doc.babylonjs.com/babylon101/lights because there's a reference to an http image http://doc.babylonjs.com/img/testlight.jpg which should be https. I can fix that in a PR, but there's also a broken image - http://blogs.msdn.com/cfs-file.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-01-44-73-metablogapi/4760.image_5F00_thumb_5F00_058CC84D.png - what should that refer to?

**Comment by deltakosh** [comment]
Thanks a lot for your help!
You can just remove the broken image for now ;)

**Comment by mthaddon** [comment]
I'd failed to notice that there's also a link to http://urbanproductions.com/wingy/babylon/misc/normals03.jpg - that site doesn't seem to support https - is there some other place we could serve this image from?

**Comment by deltakosh** [comment]
Yep just store it in public/html/imgs
