### ISSUE TITLE
Unstable behavior of occlusion culling?

### ISSUE THREAD

**Issue by LeonYuanYao** [BabylonJS/OldDocumentationSite#1557]
Hello,
Recently I’ve been testing occlusion culling in BJS. And I resulted finding some unstable behavior when setting the occlusion culling to all meshes in my scene. Some meshes flickered or disappeared when it should be seen and rendered for sure. Pls check out my screen record and the codes I posted. Any suggestions and help would be appreciated.
![录制_2019_05_24_12_17_54_95](https://user-images.githubusercontent.com/25599989/58318156-cedfda00-7e49-11e9-8996-b3f8168e57d1.gif)
![QQ截图20190524135146](https://user-images.githubusercontent.com/25599989/58318170-d606e800-7e49-11e9-9cd1-130c10df50ed.png)
![QQ截图20190524135309](https://user-images.githubusercontent.com/25599989/58318176-d901d880-7e49-11e9-8bfe-50b2ca5122ee.png)

And the playground codes: 
https://www.babylonjs-playground.com/#GLWT40

**Comment by deltakosh** [comment]
Please use our forum for questions: forum.babylonjs.com
