### ISSUE TITLE
Missing Earcut dependency in Floorplan snippet PG examples

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/OldDocumentationSite#1577]
The following documentation snippet page contains non-working PG examples due to a missing Earcut dependency:

* https://doc.babylonjs.com/snippets/house

But the related page PG examples work fine:

* https://doc.babylonjs.com/snippets/house_use

**Comment by BabylonJSGuide** [comment]
PR submitted #1578

**Comment by deltakosh** [comment]
Thanks guys!
