### ISSUE TITLE
Typescript Playground Examples Revert To Javascript Examples

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#1662]
In https://doc.babylonjs.com/features/playground in the Javascript and Typescript Examples table the playground numbers for each example are the same, the difference was in the ts.html. Since ts.html is no longer needed the Typescript PGs redirect to the Javascript PGs, eg http://www.babylonjs-playground.com/ts.html#6F0LKI to http://www.babylonjs-playground.com/l#6F0LKI

**Comment by deltakosh** [comment]
Pinging @noalak

**Comment by deltakosh** [comment]
Will be fixed with #6755
