### ISSUE TITLE
Links to API docs in guides and Babylon101

### ISSUE THREAD

**Issue by hilderonny** [BabylonJS/OldDocumentationSite#1770]
It would be helpful to have links to the corresponding API class documentation within guides and other documentation.

For example in https://babylonjsguide.github.io/basics/Cameras#arc-rotate-camera which describes the use of the Arc Rotate Camera there should be a reference to https://doc.babylonjs.com/api/classes/babylon.arcrotatecamera where one can get further information about the properties and methods of the camera.

The same is in https://doc.babylonjs.com/babylon101/cameras#arc-rotate-camera. There should also be a link to the API.

In the other direction on the API page itself a link to the guide would be helpful because the API page is often the first result when googling for ArcRotateCamera and it would be nice to find the information as fast as possible.

I would like to help you with placing those links, what should I do?

**Comment by deltakosh** [comment]
That's a good idea!

You can directly updates the .md for the guides in this repo. To get the link back from the API you need to add a \@see tag in the code like here: https://github.com/BabylonJS/Babylon.js/blob/da661ef2153e10b0e424c6f93792159b53a0a47f/src/Animations/easing.ts#L6

**Comment by thomlucc** [comment]
Closing as merged
