### ISSUE TITLE
Build API docs from source to generate links to source

### ISSUE THREAD

**Issue by edzis** [BabylonJS/OldDocumentationSite#1804]
I would like to get the standard behavior of typedoc to get a link to the source of each member.

With the help of https://github.com/gdelmas/typedoc-plugin-sourcefile-url I get the links - see https://github.com/BabylonJS/Documentation/pull/1803. But as the docs are generated not from the source but from a d.ts file that is pulled in at build time the links are not very helpful.

What would it take to start using source for API docs? Are there any blockers?

To explain my need for this, I find myself frequently jumping from docs to implementation of a method or property to get more insights in how to use a particular feature. Currently that means opening repo from the bottom navigation, searching for the class, finding the right entry in the search results, opening the file, searching for the relevant snippet and navigating to it. I want to cut that annoyance.

**Comment by deltakosh** [comment]
> What would it take to start using source for API docs? Are there any blockers?

I did not try so I don't know :) But if you want to try I will be more than happy to merge it

I won't merge the PR as the value added to point to a .d.ts file is not worth it but if we can point directly to source code that would be awesome !
