### ISSUE TITLE
`grunt serve` does not work in node v12 LTS

### ISSUE THREAD

**Issue by yamayuski** [BabylonJS/OldDocumentationSite#1843]
possibly related issue https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

```
Running "execute:compileHtmlStatics" (execute) task
Fatal Error: primordials is not defined
```

downgrade to node v10 works for me.

**Comment by deltakosh** [comment]
Ok for now let's stay with node 10, I bet grunt will make the change asap :)
