### ISSUE TITLE
Remove extra babylon101 directory?

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1858]
Would it be okay to remove the first `babylon101/` directory and pull up the second one to the `content` directory? What would be the implications of doing so? What is the deployment process to https://doc.babylonjs.com/babylon101/? Are there scripts that expect the double name?

Background: I'm using the 101 tutorial for an undergraduate class in Computer Graphics and one of our side goals is to engage students to open source development. In several classes we ask students to make a pull request. To that end, I'm asking 12-16 students to suggest (and make) change (improvements) to the tutorial. This is a trivial change (to make) that shows that one has gone through the steps, so fits within my goals. Comments and suggestions are welcome. 

Thanks!

**Comment by deltakosh** [comment]
Pinging @PirateJC

**Comment by PirateJC** [comment]
We'll be addressing this with our Documentation overhaul for 4.2. Coming soon!

**Comment by thomlucc** [comment]
Closing as it as been addressed with 4.2
