### ISSUE TITLE
Page navigation issues

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1859]
As I go through the tutorial I'm finding it difficult to navigate. For example, the first page (https://doc.babylonjs.com/babylon101/about101) has a section in the table of contents labeled 'Next' but it has no content and there is no link to the next lesson.

Suggestions:

- Every page have a link back to the top
- Every page have a link to the previous lesson as its first link
- Every page have a link to the next lesson as its last link

**Comment by deltakosh** [comment]
The next for about it to take the first step.

I will add the missing links to help with navigation

**Comment by deltakosh** [comment]
I leave this one for you ;)
