### ISSUE TITLE
Odd paragraph break in About101

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1860]
The third full paragraph has a sentence fragment that appears as a full paragraph. This was added by eb2480af4aeaf8ed973bce833c31a416a5c811ca with the comment "Fixed broken layout (the paragraph after PG example was too wide)." 

First, I don't understand how to generate the "eye" link that creates an Iframe. 

Second, we should find a way to show the link without the sentence fragment being on its own line.

**Comment by deltakosh** [comment]
> First, I don't understand how to generate the "eye" link that creates an Iframe.

It is generated when you add a link to https://www.babylonjs-playground.com/

The PG link automatically add a break to let us display the iframe for the in documentation rendering.

I will rewrite the About page to make that less weird
