### ISSUE TITLE
Explain or reference 'UV' early

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1861]
https://doc.babylonjs.com/babylon101/discover_basic_elements#face-colors-or-uv references "UV" but does not describe it. It would be helpful to have at least an early reference to something like https://en.wikipedia.org/wiki/UV_mapping, if not a brief description.

The same issue exists at https://doc.babylonjs.com/how_to/createbox_per_face_textures_and_colors.

**Comment by deltakosh** [comment]
Do you mind doing a PR to fix the page?

**Comment by deltakosh** [comment]
Will do it as well

**Comment by jgfoster** [comment]
Could you leave some easy things for my students to do?

**Comment by deltakosh** [comment]
oh my gosh yeah :D

**Comment by jgfoster** [comment]
Thanks! It was somewhat amusing to show my students the issue and suggest a fix, then go back to the page, see the reference to Wikipedia, and ask myself "How did I miss that?" One of the students then pointed out that the page had been edited during my lecture!

It is nice to see an active community, but right now I'm looking for mentors who will guide newcomers. ;-)

**Comment by deltakosh** [comment]
No problem! I will leave the updates to your students :)

You can tell them to feel free to ask any questions on our forum on forum.babylonjs.com

**Comment by Vinc3r** [comment]
If this can help ;) https://doc.babylonjs.com/how_to/contribute_to_documentation
