### ISSUE TITLE
Content clipping at the bottom of the page

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1864]
The page footer clips the bottom content.

The following is at https://doc.babylonjs.com/babylon101/first:

![Screen Shot 2020-01-29 at 7 36 22 AM](https://user-images.githubusercontent.com/1577872/73371149-1e449880-426a-11ea-9acf-db6516828e54.png)

The following is at https://doc.babylonjs.com/babylon101/discover_basic_elements:

![Screen Shot 2020-01-29 at 7 36 36 AM](https://user-images.githubusercontent.com/1577872/73371170-2270b600-426a-11ea-927b-016c4ff2066f.png)

**Comment by deltakosh** [comment]
I do not repro on my computer. Do you use specific settings like zoom or something? Which browser?

**Comment by cherbel** [comment]
The content clips on Safari but not on Google Chrome.

**Comment by deltakosh** [comment]
Rats..I don't have a mac..Interested to fix it?

**Comment by cherbel** [comment]
Sure, I can look into it.

**Comment by jgfoster** [comment]
If you find the issue and are willing to go to a bit more work, describe the fix and let one of my students go through the cycle of contributing to an open source project. Thanks!

**Comment by deltakosh** [comment]
I will for sure!!

**Comment by thomlucc** [comment]
Closing as it is now fixed in the new documentation
