### ISSUE TITLE
HTML code not consistent on First Steps

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1869]
At https://doc.babylonjs.com/babylon101/first there is sample code (above) that matches the playground and below there is an HTML template with a couple differences. Specifically,

```
var camera = new BABYLON.ArcRotateCamera("Camera", Math.PI / 2, Math.PI / 2, 2, BABYLON.Vector3.Zero(), scene);
var camera = new BABYLON.ArcRotateCamera("Camera", Math.PI / 2, Math.PI / 2, 2, new BABYLON.Vector3(0,0,5), scene);
```

and

```
var sphere = BABYLON.MeshBuilder.CreateSphere("sphere", {}, scene);
var sphere = BABYLON.MeshBuilder.CreateSphere("sphere", {diameter:2}, scene);
```

The top code seems better.

**Comment by deltakosh** [comment]
for sphere I prefer the 2nd line as it show the diameter

**Comment by riggja** [comment]
I will make this change and also look for any other inconsistencies on this page.

**Comment by thomlucc** [comment]
done
