### ISSUE TITLE
Raycasts tutorial cleanup

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1877]
Various cleanups to https://doc.babylonjs.com/babylon101/raycasts:

- Incomplete sentences ("And get the picking info."). 
- Singular/plural agreement ("Rays are ... It's used ...").
- Clarify that italicized (l.number) refers to line numbers in the demo.
- Put dot between 'l' and number (.l65).

I've asked students in CPTR 355 at WWU to tackle this issue.

**Comment by sballance** [comment]
I am in Professor Foster's class and will be working on this issue.
