### ISSUE TITLE
Sprites Tutorial Cleanup

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1878]
Placeholder for general edits to https://doc.babylonjs.com/babylon101/sprites.

- "...the minimal JSON format is." [presumably refers to the code snippet that follows]
- "which uses the first sprite on the sheet" [needs period at end of line]

Request that this issue be held for WWU CPTR 355 students. Thanks!

**Comment by nick97eagles** [comment]
I'll take care of these issues 👍🏻
