### ISSUE TITLE
Environment tutorial cleanup

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1880]
Placeholder for issues with https://doc.babylonjs.com/babylon101/environment.

- "There is [sic] two ways to create a skybox."
- The tutorial says that the skybox files need to be png but my experience is that they need to be jpg.

This is entered with the hope that it will be picked up by a student in WWU CPTR 355. (Thanks to the core team for their patience with my nit-picking as I prod the students to learn to interact in an open source community!)

**Comment by deltakosh** [comment]
> Thanks to the core team for their patience with my nit-picking as I prod the students to learn to interact in an open source community!

No problem at all! We are thrilled to help and be helped ;)
