### ISSUE TITLE
Particles Tutorial Cleanup

### ISSUE THREAD

**Issue by jgfoster** [BabylonJS/OldDocumentationSite#1894]
The documentation at https://doc.babylonjs.com/babylon101/particles contains the following sample code:

```
particleSystem.addColorGradient(0, new BABYLON.Color4(1, 1, 1, 0), new BABYLON.Color4(1, 0, 1, 0));
particleSystem.addColorGradient(1.0, new BABYLON.Color4(1, 1, 1, 1)new BABYLON.Color4(1, 0, 1, 1));
```

It appears that the second line is missing a comma and space between the second and third parameters.

This issue is intended for students in CPTR 355 at WWU. Thanks!

**Comment by lukeirvine** [comment]
I'm taking this on along with other typos in the same file.
