### ISSUE TITLE
Add note about how to allow local texture files in chrome and firefox

### ISSUE THREAD

**Issue by SentientCloud2421** [BabylonJS/OldDocumentationSite#1902]
When I was first using the texture functionality, I couldn't get it to work without using a wikimedia image. I think it would be useful to include a note about how to allow local file access. I'll be submitting a pull request to that end by midnight tonight. Please don't make this change before me, as this is a required assignment for me.

**Comment by deltakosh** [comment]
Yeah this is a really good point
