### ISSUE TITLE
Filter search for 'VR' should bring up WebXR docs

### ISSUE THREAD

**Issue by lazerwalker** [BabylonJS/OldDocumentationSite#1975]
When I was first getting started with Babylon.js, the way I jumped into setting up a VR scene as a brand new user was to go to the "How To..." tab of the doc website and to search for "VR".

This search had two results, the WebVR camera and WebVR experience helper docs, which in turn led me down a rabbithole of linked WebVR-focused docs. This was despite the fact that I was doing this well after the WebXR experience helper had been created and was the preferred method. (See: #1974)

In an ideal world, searching for "VR" on the "How To..." filter screen should bring up all WebXR focused docs instead of just WebVR ones. I don't know if this is easily possible with the way the filter box is implemented, I suspect it might currently just be a plaintext search of article titles. This is probably less of a critical issue if #1974 gets merged, but wanted to raise it anyway.

FWIW, the global search in the top-right corner of the docs UI does properly return WebXR content for a search for the term "VR". What I've described specifically only happens in the filter search on pages, such as the "How To..." list.

**Comment by Yonet** [comment]
Also related issue, searching examples for WebXR doesn't return any results. Thanks!

![webXRNotFound](https://user-images.githubusercontent.com/3523671/89697152-b71a3780-d8cf-11ea-9945-7d2a6c5f7330.png)

**Comment by deltakosh** [comment]
I think this is because there is no WebXR example yet :)
We can add them pretty easily here: https://github.com/BabylonJS/Documentation/blob/master/examples/list.json

**Comment by RaananW** [comment]
Need to address both of those. 
Regarding the search - I will make sure to add a large disclaimer on VR-related documentation to go try WebXR instead, and will add VR as a keyword to the XR pages.

I'll also add a few examples to the examples page (and remove the WebVR exampl(s)

**Comment by thomlucc** [comment]
Closing per Raanan for #1 and for  #2 (webXR Search) is now working
