### ISSUE TITLE
Arc Rotate Camera Contradiction in Docs

### ISSUE THREAD

**Issue by tahteche** [BabylonJS/OldDocumentationSite#1987]
In the docs here: https://doc.babylonjs.com/babylon101/cameras#arc-rotate-camera

It's stated that `Both alpha and beta increase in a clockwise direction.` but the following diagram that accompanies the text shows alpha increasing in an anti-clockwise direction.

![camalphabeta](https://user-images.githubusercontent.com/6853998/86176699-ef697180-baea-11ea-82a1-9e50d58cde4b.jpg)

**Comment by sebavan** [comment]
I ll change it ASAP thanks
