### ISSUE TITLE
Recreating the default configuration for the viewer has an error

### ISSUE THREAD

**Issue by pocce90** [BabylonJS/OldDocumentationSite#1999]
At the end of this tutorial (https://doc.babylonjs.com/extensions/recreating_the_default_configuration#templates-main-template) there is a full code demonstration that doesn't work. If you try to press play button, or other buttons like full screen mode or the timeline bar there are no effects on the scene. I tried directly in my solution and there are no errors in console

**Comment by RaananW** [comment]
Hi, will look into that! thanks for reporting
