### ISSUE TITLE
Page not found errors on local version of Documentation

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/OldDocumentationSite#2002]
Some menu items of the documentation return a page not found error

Repro:
- Following how to contribute to the doc: https://doc.babylonjs.com/how_to/contribute_to_documentation
- When building the doc locally some menu items of the documentation return a page not found error. 
For example clicking on Balylon 101:
![image](https://user-images.githubusercontent.com/32072891/87823555-79724380-c828-11ea-894b-30639e175e32.png)
Gives:
![image](https://user-images.githubusercontent.com/32072891/87823819-f3a2c800-c828-11ea-9f2c-42e558f81344.png)

-> Menu not working: "Babylon 101",  "How To", "Features", "Resources",  "Extensions", "Snippets"
-> Menu working: "Home", "What's new", "Examples", "API", "Playground

**Comment by RaananW** [comment]
Just making sure - did you run the `build` task before?

I get the page rendered:

![image](https://user-images.githubusercontent.com/1381702/88050733-b192c280-cb57-11ea-8c6d-24a5c84718ed.png)

But I agree that build should execute automatically before serve (or better yet - during!)

**Comment by RaananW** [comment]
This is related to the node version used to build the documentation page. at the moment we only support node < 12, due to grunt's dependencies. This will change soon.
