### ISSUE TITLE
ArcRotationCamera.setTarget has different argument type than set target()

### ISSUE THREAD

**Issue by valen214** [BabylonJS/OldDocumentationSite#2019]
Quick problem

the two lines below are the implementation
[`arcRotateCamera.ts (line 975): setTarget(target: AbstractMesh | Vector3, ...)`](https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/arcRotateCamera.ts#L975) takes `Vector3 | AbstractMesh` as first argument

[`arcRotateCamera.ts (line 63): set target(value: Vector3)`](https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/arcRotateCamera.ts#L63) takes only `Vector3` as the first argument `value` while the implementation is literally `{ this.setTarget(value); }`

corresponding [typedoc line 42664 for `set target()`](https://github.com/BabylonJS/Documentation/blob/master/typedoc/babylon.d.ts)

so it is actually possible to do `camera.target = mesh as any`

I suggest [`set target()`](https://doc.babylonjs.com/api/classes/babylon.arcrotatecamera#target) should include some guidance to notify viewers that `camera.target = mesh` is possible,
or something like "`set target() is just an alias to `[`setTarget()`](https://doc.babylonjs.com/api/classes/babylon.arcrotatecamera#settarget)"
`set target()` comes first in the documentation (typedoc), it's reasonable for people skim through and think `set target()` and `setTarget()` take the same type then omit the feature `setTarget` offers. (I think? at least it happened on me :(
It took me a day to discover that feature, seeing some PG actually used `camera.target = mesh`, I was shocked because I thought it can only be `Vector3`)

edit: oddly [setTarget(Vector3) in UniversalCamera](https://doc.babylonjs.com/api/classes/babylon.universalcamera#settarget) has it mentioned, even the parameter type is still the same

**Comment by valen214** [comment]
recommend to add `incomplete doc` label if necessary

**Comment by deltakosh** [comment]
Well I would not like to complicate things here. The target property is inherited from TargetCamera where only vector3 is supported

And furthermore the set target will be different than the get as the getter only returns vector3

**Comment by deltakosh** [comment]
I'll add a note though :)

**Comment by deltakosh** [comment]
"Please note that you can set the target to a mesh and thus the target will be copied from mesh.position"
