### ISSUE TITLE
Animation blending PG in docs is broken

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/OldDocumentationSite#2030]
https://www.babylonjs-playground.com/#2BLI9T#174 from https://doc.babylonjs.com/babylon101/animations#animation-blending

The PG is referencing the FPS HTML element which is no longer available after the React conversion.

**Comment by PirateJC** [comment]
fixed with new playground:
https://www.babylonjs-playground.com/#2BLI9T#368
