### ISSUE TITLE
"How to use Babylon.js with ReactJS" wrong links

### ISSUE THREAD

**Issue by mihainsto** [BabylonJS/OldDocumentationSite#2034]
At the bottom of the page the links are inversed, if you click on the TS source it redirects you to JS source, and if you click the JS source you get redirected to the TS source. 

We can see this in the page source: 
https://github.com/BabylonJS/Documentation/blob/master/content/resources/Library/BabylonJS_and_ReactJS.md

```
> * JavaScript (examples for 3D models, GUI, VR, behaviors, props/state management)
>   * [source](https://github.com/brianzinn/create-react-app-typescript-babylonjs)
>   * [demo](https://brianzinn.github.io/create-react-app-babylonjs/)
> * TypeScript (GUI + physics + shadows)
>   * [source](https://github.com/brianzinn/create-react-app-babylonjs)
>   * [demo](https://brianzinn.github.io/create-react-app-typescript-babylonjs/)

```

I think that we can fix this by simply swapping the links.

**Comment by sebavan** [comment]
Done and thanks !!!
