### ISSUE TITLE
'jsut' Spelling mixed up issue on document doc.babylonjs.com/how_to/webxr_augmented_reality page

### ISSUE THREAD

**Issue by jithinagiboson** [BabylonJS/OldDocumentationSite#2039]
doc.babylonjs.com/how_to/webxr_augmented_reality

just search for the keyword 'jsut'

on 

You might ask yourself why use the anchor system with hit-test results, as hit-test results are returned by the system with a position defined by the device. Setting the mesh at the hit-test's location will work **jsut** fine

location just above 

### Plane detection
Your device is (usually) capable of detecting plane geometries in the real world. To read more about plane detection go to the Plane detection explainer.

**section**

**Comment by BabylonJSGuide** [comment]
Hi @jithinagiboson, well spotted. Would you like to submit a correction? https://doc.babylonjs.com/how_to/contribute_to_documentation#the-easy-way

**Comment by PirateJC** [comment]
Thanks for finding this! It's fixed in the new documentation pages that will be released with version 4.2. Changes won't be visible until then.
