### ISSUE TITLE
Incorrect method for customizing camera inputs

### ISSUE THREAD

**Issue by saaratrix** [BabylonJS/OldDocumentationSite#2042]
Hi I was implementing custom inputs for a camera and on this page:
https://doc.babylonjs.com/how_to/customizing_camera_inputs

It's mentioning this method several times: `getTypeName` 

But it should actually be `getClassName` 

This is the actual interface:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/cameraInputsManager.ts#L16

**Comment by saaratrix** [comment]
I made a PR for the documentation changes and I noticed that in the camera inputs manager there is a typo (intput) :):
https://github.com/BabylonJS/Babylon.js/blob/master/src/Cameras/cameraInputsManager.ts#L22

**Comment by PirateJC** [comment]
This is changed and fixed in the new documentation pages, coming with the 4.2 release. Changes will not be visible until then.
