### ISSUE TITLE
Markdown messed up on Position, Rotation, Scaling page

### ISSUE THREAD

**Issue by pan-long** [BabylonJS/OldDocumentationSite#23]
As shown in the screenshot.
url: http://doc.babylonjs.com/tutorials/03._Position,_Rotation,_Scaling

![screenshot-doc babylonjs com 2016-02-15 14-27-14](https://cloud.githubusercontent.com/assets/4057238/13041238/6bad4406-d3f0-11e5-96cb-ebe533cc2e6c.png)

**Comment by RaananW** [comment]
thank you, formatting solved.
