### ISSUE TITLE
search not working on doc site?

### ISSUE THREAD

**Issue by boyofgreen** [BabylonJS/OldDocumentationSite#291]
Hi Guys, it seems like the search isn't working on the doc site.  I get a 500 error when I try to search in edge

**Comment by deltakosh** [comment]
Hey my friend:)
Yes it is utterly slow for some reasons. Our Azure god (@raananW) is summoning some demons from hell to try to fix it

**Comment by RaananW** [comment]
Howdy partners,

the jquery CDN is offline for some reason. I guess half of the world is wondering what happens!
The server is running correctly, I will wait a bit and see when they fix it or change to a different CDN.
