### ISSUE TITLE
playgrounds broke in Documentation/content/extensions/MaterialsLibrary/Water.md 

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#422]
It seems that ocean shader doesn't work on playgrounds examples : 
* http://www.babylonjs-playground.com/#1SLLOJ#15
* http://www.babylonjs-playground.com/#1SLLOJ#17
* http://www.babylonjs-playground.com/#1SLLOJ#18
* http://www.babylonjs-playground.com/#1SLLOJ#19
* http://www.babylonjs-playground.com/#1SLLOJ#20

**Comment by CraigFeldspar** [comment]
Seems like it's still the old waterMaterial.js - that doesn't support UBO - which is used : `e.MaterialHelper.PrepareUniformsAndSamplersList(d,p,n,this.maxSimultaneousLights)` against `                BABYLON.MaterialHelper.PrepareUniformsAndSamplersList({
                    uniformsNames: uniforms,
                    uniformBuffersNames: uniformBuffers,
                    samplers: samplers,
                    defines: defines,
                    maxSimultaneousLights: this.maxSimultaneousLights
                });`

But the shader used is the new UBO one.

@deltakosh, how is material library handled in the playground ?

**Comment by deltakosh** [comment]
My bad.. I'll deploy the new mat lib

**Comment by deltakosh** [comment]
You can do it if you want by updating the files here:https://github.com/BabylonJS/Website/tree/master/lib

**Comment by deltakosh** [comment]
Fixed
