### ISSUE TITLE
Broken link AND folder no found

### ISSUE THREAD

**Issue by stephstephsteph** [BabylonJS/OldDocumentationSite#424]
I run the command "grunt serve watch" and problem ... show:

**Error: ENOENT: no such file or directory, scandir 'C:\Users\steph\Documents\DEVELOPPEMENT\DOCUMENTATIONS\BabylonJS_DOC\Documentation\data\search'**

I create the folder "search" ... Yes i see the page web "localhost:3000", but I click on tab "tutorial" And I click on another choice. Example: "Cameras" and boom: **"404. Page not found"** 

I see in the url there is a duplicate, example(tutorials/tutorials):
**localhost:3000/**tutorials**/tutorials/Cameras.**
Same thing for others:

Thanks!

**Comment by Jaskar** [comment]
https://github.com/BabylonJS/Documentation/pull/428

**Comment by Jaskar** [comment]
After testing it, won't work.
