### ISSUE TITLE
Links to documentation in tutorials

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#492]
Many tutorials have links to documentation, some use broken links. They are often under this forms : 
http://doc.babylonjs.com/classes/2.5/deviceorientationcamera (actual correct link) or http://doc.babylonjs.com/classes/deviceorientationcamera

It's kind of painstaking work to update them all.

Is there a way to make permanent links to an element in doc', even when the doc will update to 3.0 ? (links will be http://doc.babylonjs.com/classes/3.0/deviceorientationcamera I guess ?).
Maybe somethings like url rewriting or global php variables ?

(I submit this question 'cause I haven't enough skills to know if this possible :) )

**Comment by Vinc3r** [comment]
Maybe a manual technique could be to open all .md, and doing a find & replace, but it can create bugs if we don't pay attention.

**Comment by deltakosh** [comment]
Yes I think it could work
I'll give a try

**Comment by deltakosh** [comment]
Can you point me to a broken one?

**Comment by deltakosh** [comment]
Should be good now
