### ISSUE TITLE
Documentation for CreateScreenshot

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#525]

**Comment by fabsharp** [comment]
Do I have to use existing [Render_Scene_on_a_PNG.md](https://github.com/BabylonJS/Documentation/blob/master/content/How_To/scene/Render_Scene_on_a_PNG.md) ? There are some dead links and - no offense - but it's not very helpfull :p .

**Comment by BabylonJSGuide** [comment]
Thank you for bringing the dead links to our notice. Without users bringing them to our notice they are easily missed. The links are to an external website that no longer appears to be available and they will have to be recreated and stored internally.  It does give users a choice of using CreateScreenshot or PrtScr so IMHO it remains but needs new images.

**Comment by deltakosh** [comment]
Agree with @babylonjsguide 
Do not under estimate what people may need. We are not all skilled developers like you

**Comment by fabsharp** [comment]
@BabylonJSGuide, @deltakosh, the "not very helpfull" wasn't appropriate sorry !

**Comment by deltakosh** [comment]
No worry:)

**Comment by BabylonJSGuide** [comment]
Have updated the page. Depending on whether I have misunderstood how to apply CreateScreenshot or not there may be a couple of issues with the original article. These I have corrected. If I have misunderstood please let me know how the following two things can be achieved and I will correct my update and provide examples.

1.
Original - Another cool aspect of using this feature is that you can use a non-active camera to create the screenshot, so you can produce many screenshots, without switching cameras!**
**** I cannot get different views by using an inactive camera.

2. If you want to have a custom width and height (like 600x400) .......... implication is that you can change the aspect ratio of the image - whereas it seems to me that the rendered image is placed in its correct aspect ratio in the center of a created image of the given size.

I will leave this issue open until the above points are cleared up.

**Comment by sebavan** [comment]
Hello @BabylonJSGuide ,

About 1. The camera is only use to collect the desired aspect ratio. The rendered image will be the canvas itself in any case. I am suspecting it is to prevent weird artifacts on the canvas during the screenshot. Bascially rendering from a special camera needs to be addressed through the CreateScreenshotUsingRenderTarget function.

About 2. correct aspect ratio does not change but rendered image is placed in the middle of the created image.

Please, let me know if I am not clear enough.
