### ISSUE TITLE
Documentation for scene construction helpers

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#530]
Need a simple doc to present how to use createDefaultCameraOrLighting and createDefaultSkybox

https://www.babylonjs-playground.com/#SIB60G#4

**Comment by brian-hay** [comment]
@deltakosh I could have a go at this.

Let me know if there's any other doc priorities, especially English review/rewrite stuff.

**Comment by deltakosh** [comment]
Any issue here is important so feel free to pick this one

**Comment by deltakosh** [comment]
Thanks a lot btw

**Comment by brian-hay** [comment]
I can't seem to assign myself, or do you need to do that?

**Comment by deltakosh** [comment]
I can't either as you did not create the issue. But consider it yours!

**Comment by brian-hay** [comment]
OK.

**Comment by brian-hay** [comment]
I'm a little confused about the difference between **createDefaultCamera()** & **createDefaultCameraOrLight()** - in the Class API docs they seem to have the same method parameters, but only the latter method is in the source code, so I'm assuming it's a temporary doc generation glitch?

Do you want these docs in 101, how to or features section? And with createDefaultCameraOrLight() most other documentation like this that I see is subcategorised under "light" or "camera" - it can't be tagged both as far as I can see. So unclear where exactly it should go.

I'll stop bothering you when I more familiar with the doc structure. It's just because I'm new ...

**Comment by brian-hay** [comment]
Sorry I see createDefaultCamera() in 3.2.0-beta.1 and I understand the intent there, so disregard that question.

But question of where docs should ideally go still stands.

**Comment by BabylonJSGuide** [comment]
The sections are loosely intended as

features - this gives an overview of the features of BJS objects in categories and usually just gives a brief mention and short description with links to a more detailed explanation in 101 or How To. Probably these methods get a mention in the scene section of features and could also get a mention in camera, lights and environment sections of features

101 - read through from start to finish as a basic introduction to Babylon.js with examples to build a starter project. So possibly added detail in the camera, lights and environment pages

How To - detailed explanations and examples of features beyond 101. Never any harm in repeating small sections so an example in http://doc.babylonjs.com/how_to/load_from_any_file_type might not got amiss.

Sorry not to be more precise but other than where to place these methods is not entirely clear to me.

**Comment by deltakosh** [comment]
I could see a new chapter here about **helpers:**
http://doc.babylonjs.com/features/scene

We could even reference the scene.createDefaultEnvironment (Which is detailed in the environment 101) and the scene.createDefaultVRExperience (Which has its own chapter)

**Comment by brian-hay** [comment]
New section **helpers** it is. Thanks @deltakosh and @BabylonJSGuide 

Will aim to get it done within the next week.

**Comment by deltakosh** [comment]
Much appreciated

**Comment by BabylonJSGuide** [comment]
Good plan

**Comment by deltakosh** [comment]
up?

**Comment by BabylonJSGuide** [comment]
Issue #1101 was a re-statement of this and has now been dealt with.
