### ISSUE TITLE
Add images in tutorials

### ISSUE THREAD

**Issue by dad72** [BabylonJS/OldDocumentationSite#533]
I would see images of presentation of each mesh in this tutorial for example.

[http://doc.babylonjs.com/tutorials/mesh_createxxx_methods_with_options_parameter](http://doc.babylonjs.com/tutorials/mesh_createxxx_methods_with_options_parameter)

I think there are tutorials that should have pictures (for illustrated). I mean there are a lot of tutorials that only feature you text. Adding images can help you know what it's all about at a glance.

Exemple in this doc :
http://doc.babylonjs.com/tutorials/in-browser_mesh_simplification_(auto-lod)

3 images that presents a decimer models could be enough to see what it is about.

I could probably help here if I only have pictures to add.

**Comment by deltakosh** [comment]
Like the idea

**Comment by jbousquie** [comment]
is there a place (server/domain name) where to store these images then ? (github doesn't really allow to store images)

**Comment by deltakosh** [comment]
We store them here: https://github.com/BabylonJS/Documentation/tree/master/public/html/img

**Comment by deltakosh** [comment]
CLosing for now. Please reopen if still alive :)
