### ISSUE TITLE
Documentation for Blender exporter

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#556]
I'm on it, trying to finish first version as soon as possible ;)
Everyone can (should?) suggest ideas/enhancement/requests/etc, here, or [in the forum](http://www.html5gamedevs.com/topic/36596-blender-exporter-doc-needs-feedback/).

Right now, this is the todo-list:

- [ ]  finish features list [quite done, need polishing and missing some cycles options],
- [ ] add good practice for amature animation ([example](http://www.html5gamedevs.com/topic/32271-importing-animations-mixamo/?do=findComment&comment=184996)),
- [x] add [color settings tip](http://www.html5gamedevs.com/topic/31708-solved-bjs-colors-different-from-blender/?do=findComment&comment=182163): [(job done)](http://doc.babylonjs.com/exporters/blender_tips#color-conversion)
- [ ] how works meshes instances [(example)](http://www.html5gamedevs.com/topic/36320-issues-with-instances-created-in-blender/)
- [x] Merge _/resources/installing__the_babylon_exporter/_ page directly into _/resources/blender/_ page
- [x] once task above done, delete installation part in this [readme](https://github.com/BabylonJS/Exporters/blob/master/Blender/readme.md)
- [ ] how works different types of animations
- [x] add a changelog.md ([example](http://www.html5gamedevs.com/topic/36076-blender-exporter-version-56/))
- [x] add a _Blender to glTF_ page
- [x] add an html example/snippet to quickly test our exported .babylon file (maybe already existing in the doc? if so, add a link to)

**Comment by deltakosh** [comment]
Wonderful!!

**Comment by deltakosh** [comment]
what's up here?

**Comment by Vinc3r** [comment]
Since few weeks I haven't so much time to give to the doc', sorry ! :-/ 
I think the first steps is done, but I still have some ideas to enhance it... but for now I don't know when I could.

**Comment by deltakosh** [comment]
Up?:)

**Comment by Vinc3r** [comment]
Yep you're right, time to enhance the doc. I'll try to do that.

**Comment by Vinc3r** [comment]
#1031 
#1038
#1073

**Comment by Vinc3r** [comment]
sorry about this issue still not closed, but 'still haven't enough time to enhance it these (many) days (plus 'can't use too much my computer during the current heatwave here, if I want to be able to sleep in decent temperatures :) )

**Comment by Vinc3r** [comment]
I think this issue can be closed, or maybe assigned to JCPalmer?

Since maybe a year I use exclusively gltf format so I'm not anymore aware about the .babylon Blender exporter.

**Comment by deltakosh** [comment]
Yes I agree let's close it
