### ISSUE TITLE
Tutorial on Cameras, Mesh Collisions and Gravity

### ISSUE THREAD

**Issue by magp3** [BabylonJS/OldDocumentationSite#573]
http://doc.babylonjs.com/tutorials/cameras,_mesh_collisions_and_gravity

~~The part with gravity does not seem to work. Not sure if I'm missing something..I thought perhaps the tutorial is outdated?~~

I realized that I need the physics engine enabled for this to work. I think the example code does not mention this and is rather confusing? What do I need the ellipsoid for if the physics engine is doing the collision checking? Is that just for the camera?

Reprod here:
https://www.babylonjs-playground.com/#4HUQQ#202

**Comment by deltakosh** [comment]
Hey do you mind asking this question on the forum? 
And yes you are totally right, you were looking for physics as collisions only apply to FreeCamera.

Perhaps the doc is not clear enough :(
