### ISSUE TITLE
Indentation inconsistencies with bullet lists

### ISSUE THREAD

**Issue by ranveeraggarwal** [BabylonJS/OldDocumentationSite#599]
I just started using/learning BabylonJS through the tutorials and noticed some inconsistencies in the bullet lists starting [here](http://doc.babylonjs.com/tutorials/discover_basic_elements).

![screenshot](https://user-images.githubusercontent.com/3941281/31272185-b361e66e-aaa7-11e7-88ba-8ec52b7bece0.png)

[Next tutorial](http://doc.babylonjs.com/tutorials/materials) onwards, the indents seem to be completely missing. It would be great to have content indented with the list item it belongs to. Since this is markdown, a few newlines/tabs ought to fix this (a script with a regex replace could be written maybe, since this looks like a recurring issue).

Apologies for spam if this is known and is being worked upon. If not, I can work on a PR over the weekend.

**Comment by RaananW** [comment]
Hi,

We can work on that - the solution is rather straight-forward (as you say - a few newlines to be removed). Want to help out with a pull-request?

**Comment by ranveeraggarwal** [comment]
Sure, I will send a PR soon 😄

**Comment by ranveeraggarwal** [comment]
There seems to be an issue with the current markdown engine. 

When I try something like

```
* Text1
    Text2
    * Text3
    
    Text4
```

Instead of rendering as 

* Text1
    Text2
    * Text3
    
    Text4

It renders as 

* Text1
    Text2
    * Text3
    Text4

Would you consider changing/updating your markdown engine? Alternatively, you could use HTML tags for nested lists.

**Comment by deltakosh** [comment]
cc @temechon

**Comment by ranveeraggarwal** [comment]
My bad, it worked with a 2-space indentation. The markdown engine here is not 4-space indentation sensitive. This should probably be mentioned in the contributing guide/vscode settings.
