### ISSUE TITLE
Missing image in Cameras, Mesh Collisions and Gravity Tutorial (9)

### ISSUE THREAD

**Issue by ranveeraggarwal** [BabylonJS/OldDocumentationSite#601]
The image here seems to be missing. I can see a link in the markdown, but it gives a 404.

<img width="830" alt="screen shot 2017-10-07 at 12 47 41 am" src="https://user-images.githubusercontent.com/3941281/31294613-2dbcfdf8-aaf9-11e7-8f55-1884a6656eb0.png">

**Comment by deltakosh** [comment]
Do you mind to submit a PR to remove the images?
