### ISSUE TITLE
Create VR Resource

### ISSUE THREAD

**Issue by ashanhol** [BabylonJS/OldDocumentationSite#628]
There's currently no guide under General, Tutorials, or Overviews that details the VR offerings from Babylon.js. 

I plan to create a guide that would show things such as: 
- Creating a reticle
- VR input/cameras
- UI (used for something like score)
- spatialized sound

(I'd self assign if I could)

**Comment by deltakosh** [comment]
This is great:) please just wait for the big PR to be nerged
