### ISSUE TITLE
Rename how_to to How To

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#634]

**Comment by RaananW** [comment]
note that this might require reindexing the how-to tutorials, please let me know when it is done.

**Comment by QuentinRillet** [comment]
Hi @deltakosh ,

Where is it ?

**Comment by RaananW** [comment]
The search results have how_to in their title (for example - http://doc.babylonjs.com/search?q=highlight ) That's the first place I could find it in.

**Comment by deltakosh** [comment]
Exactly. It is in every page from the how to (in the header)

**Comment by BabylonJSGuide** [comment]
Having tried to use a space instead of _ in How_To and having got into all sorts of issues with internet URLS I ended up with doing a replace in the static.pug and statics.pug files for 

h1=staticContent.category.replace("_", " ") and

h1=dataObj.category.replace("_"," ") respectively.

This seems to me to be the easiest way to do it in the search results as well and so suggest the following changes in search.js on lines 73 and 83. I will not do a push for this in case this is not the way you want to go. Not sure if there are other places the how to hyphen appears but assume a similar solution would work.


                html += '<div class="basicFilter disabled"  data-version="' + cat + '"><span>' + cat.replace(/_/, " ") + '</span><span>(' + numOfFiles + ')</span></div>';


                html += '<a href="' + f.src + '">' + f.version.replace(/_/, " ") + ' : ' + f.name + '</a>';

**Comment by deltakosh** [comment]
Ping @temechon and @quentinrillet

**Comment by BabylonJSGuide** [comment]
Woops a few days ago I tested out my idea for replacing _ in How_To with a local build and it worked. In my last commit these changes in search.js were still in place so got committed and pushed. Honestly I am not trying to take over the documentation (or perhaps it is just my first step to world domination :) )

**Comment by deltakosh** [comment]
Which commit was it?

**Comment by BabylonJSGuide** [comment]
ced79cc but please note that though the change was not supposed to have been left in it does appear to solve the hyphen problem. Leave it to you as to what you want to do.

**Comment by deltakosh** [comment]
This is perfect :)

**Comment by RaananW** [comment]
Should I reindex the how-tos?

**Comment by deltakosh** [comment]
Nope that's the magic of it

**Comment by RaananW** [comment]
They are still shown as How_To in the search index - http://doc.babylonjs.com/search?q=highlight (even after reindexing)

**Comment by deltakosh** [comment]
Ah ! Right. We need to do the little replace trick here as well:)
Ping @quentinrillet

**Comment by RaananW** [comment]
And then I'll have to reindex ;)

**Comment by deltakosh** [comment]
Sure you like it

**Comment by deltakosh** [comment]
Can we reindex? ping @QuentinRillet

**Comment by Kimoen** [comment]
I don't see any underscores in the search result... It seems it has already been done: https://github.com/BabylonJS/Documentation/commit/ced79cc8c04164ecb2066049601bfc339148138d#diff-7150cea0f9818367b6d63c04bcfead00
And I don't think we need to reindex as everything is in the js. But if you really want to reindex, you can do it :)

**Comment by deltakosh** [comment]
Good :)
