### ISSUE TITLE
Mention kernelBlur on mirror documentation

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#655]
http://doc.babylonjs.com/how_to/reflect#mirrors

Sample:
https://www.babylonjs-playground.com/#LVTTQX#1

**Comment by deltakosh** [comment]
MirrorTexture can support blurred rendering with either:
* adaptiveBlurKernel: setting this value to something else than 0 will blur the texture with a specified kernel (the bigger the blurrier). Value will be adapted to the viewport size
* blurKernel: same as adaptiveBlurKernel proeprty but the value is not adapted to viewport size

**Comment by BabylonJSGuide** [comment]
Done
