### ISSUE TITLE
Remove obsolete importer code

### ISSUE THREAD

**Issue by mootari** [BabylonJS/OldDocumentationSite#714]
The repo currently contains `/scripts/helpers/importer` which seems to have been used in the past to migrate content from a now defunct[ old documentation site](http://babylondoc.azurewebsites.net).

I suggest to remove this code to make it easier for contributors to find their way around the source.

The (currently non-functioning) forwarder code for old php-style URLs needs to be replaced with a static list of redirects. Duplicate IDs in the lists below are marked with `(D)`.

<details>
<summary>PHP links used in BJS docs</summary>

|ID|Page
|:-|:-
|21911|content/babylon101/babylon101/First.md
|22081|content/babylon101/babylon101/Animations.md
|22531|content/How_To/events/How_to_use_Actions.md
|22581|content/How_To/scene/How_to_use_SceneOptimizer.md
|22591|content/How_To/mesh/How_to_use_LOD.md
|22601|content/How_To/material/How_to_use_Procedural_Textures.md
|22611|content/features/PGsupport/Playground_debuglayer.md
|24822|content/How_To/mesh/In-Browser_Mesh_Simplification.md
|24824|content/How_To/audio/Playing_sounds_and_music.md
|24825|content/How_To/material/How_to_use_DepthRenderer_to_get_depth_values.md
|24827|content/How_To/Videos/3D_on_the_Web_Understanding_the_Basics.md
|24828|content/How_To/Videos/WebGL_Basics.md
|24829|content/How_To/Videos/Using_Babylon.js_for_Beginners.md
|24830|content/How_To/Videos/Understanding_Materials_and_Inputs.md
|24831|content/How_To/Videos/Game_Pipeline_Integration_with_Babylon.js.md
|24832|content/How_To/Videos/Loading_Assets.md
|24833|content/How_To/Videos/Babylon.js_Advanced_Features.md
|24834|content/How_To/Videos/Special_Effects.md
|24837|content/How_To/Post_Process/Using_the_SSAO_rendering_pipeline.md
|24840|content/How_To/light/Using_the_Volumetric_LightScattering_post-process.md
|24841|content/How_To/Post_Process/Using_depth-of-field_and_other_lens_effects.md
|24847|content/babylon101/babylon101/Parametric_Shapes.md
|25088|content/How_To/mesh/Ribbon_Tutorial.md
|25090|content/How_To/mesh/How_to_use_Path3D.md
|25091|content/How_To/mesh/How_to_use_Curve3.md
|25094|content/How_To/mesh/Decals.md
|25096|content/How_To/mesh/How_to_dynamically_morph_a_mesh.md
|25109|content/How_To/Importer/STL.md
</details>

<details>
<summary>Complete list of content page IDs</summary>

|ID|Page
|:-|:-
|20|content/resources/Exporter/3DSMax.md
|21|content/resources/Exporter/Blender.md
|22011|(D) content/babylon101/babylon101/Discover_Basic_Elements.md
|22011|(D) content/How_To/mesh/Set_Shapes.md
|22041|content/features/component/Position,_Rotation,_Scaling.md
|22051|content/babylon101/babylon101/Materials.md
|22061|content/babylon101/babylon101/Cameras.md
|22071|content/babylon101/babylon101/Lights.md
|22081|content/babylon101/babylon101/Animations.md
|22082|content/babylon101/babylon101/Sprites.md
|22091|content/babylon101/babylon101/Cameras,_Mesh_Collisions_and_Gravity.md
|22101|content/babylon101/babylon101/Intersect_Collisions_-_mesh.md
|22111|content/babylon101/babylon101/Picking_Collisions.md
|22121|content/babylon101/babylon101/Particles.md
|22131|content/babylon101/babylon101/Environment.md
|22141|content/babylon101/babylon101/Height_Map.md
|22151|(D) content/babylon101/babylon101/Raycasts.md
|22151|(D) content/babylon101/babylon101/Shadows.md
|22231|content/How_To/scene/Caching_Resources_in_IndexedDB.md
|22251|content/How_To/Importer/Using_the_Incremental_Loading_System.md
|22421|content/How_To/mesh/How_to_use_Bones_and_Skeletons.md
|22431|content/How_To/Post_Process/How_to_use_PostProcesses.md
|22441|content/How_To/Post_Process/How_to_use_PostProcessRenderPipeline.md
|22451|content/How_To/mesh/How_to_Merge_Meshes.md
|22461|content/How_To/camera/How_to_use_Multi-Views.md
|22471|content/How_To/environment/How_to_use_Lens_Flares.md
|22481|content/How_To/material/How_to_use_FresnelParameters.md
|22491|content/How_To/Importer/How_to_Create_Your_Own_File_Importer.md
|22511|content/How_To/Physics/Adding_Your_Own_Physics_Engine_Plugin_to_Babylon.js.md
|22531|content/How_To/events/How_to_use_Actions.md
|22551|content/How_To/Importer/How_to_use_AssetsManager.md
|22561|content/How_To/scene/Optimizing_Your_Scene_with_Octrees.md
|22571|content/How_To/mesh/How_to_use_Instances.md
|22581|content/How_To/scene/How_to_use_SceneOptimizer.md
|22591|content/How_To/mesh/How_to_use_LOD.md
|22601|content/How_To/material/How_to_use_Procedural_Textures.md
|22641|content/resources/Reference/Creating_the_Mini-fied_Version.md
|22661|content/resources/Reference/File_Format_Map_(.babylon).md
|22671|content/How_To/contribute/Approved_Naming_Conventions.md
|22691|content/How_To/scene/Render_Scene_on_a_PNG.md
|24441|content/resources/Exporter/Cheetah3D.md
|24821|content/resources/Exporter/Installing__the_Babylon_Exporter.md
|24822|content/How_To/mesh/In-Browser_Mesh_Simplification.md
|24824|content/How_To/audio/Playing_sounds_and_music.md
|24825|content/How_To/material/How_to_use_DepthRenderer_to_get_depth_values.md
|24826|content/How_To/Videos/Video_courses.md
|24827|content/How_To/Videos/3D_on_the_Web_Understanding_the_Basics.md
|24828|content/How_To/Videos/WebGL_Basics.md
|24829|content/How_To/Videos/Using_Babylon.js_for_Beginners.md
|24830|content/How_To/Videos/Understanding_Materials_and_Inputs.md
|24831|content/How_To/Videos/Game_Pipeline_Integration_with_Babylon.js.md
|24832|content/How_To/Videos/Loading_Assets.md
|24833|content/How_To/Videos/Babylon.js_Advanced_Features.md
|24834|content/How_To/Videos/Special_Effects.md
|24837|content/How_To/Post_Process/Using_the_SSAO_rendering_pipeline.md
|24840|content/How_To/light/Using_the_Volumetric_LightScattering_post-process.md
|24841|content/How_To/Post_Process/Using_depth-of-field_and_other_lens_effects.md
|24847|content/babylon101/babylon101/Parametric_Shapes.md
|25088|content/How_To/mesh/Ribbon_Tutorial.md
|25089|content/resources/Exporter/Bones_influences_per_vertex.md
|25090|content/How_To/mesh/How_to_use_Path3D.md
|25091|content/How_To/mesh/How_to_use_Curve3.md
|25094|content/How_To/mesh/Decals.md
|25095|content/resources/Exporter/Blender_Tips.md
|25096|content/How_To/mesh/How_to_dynamically_morph_a_mesh.md
|25100|content/resources/Manual/Transparency_and_How_Meshes_Are_Rendered.md
|25101|content/How_To/environment/Supporting_fog_with_ShaderMaterial.md
|25109|content/How_To/Importer/STL.md
|25363|content/How_To/camera/Layermasks_and_Multi-Cam_Textures.md
|25364|content/How_To/material/How_to_use_Blend_Modes.md
|29000|content/How_To/camera/Customizing_Camera_Inputs.md
|45094|content/resources/Manual/Normals.md
|925088|content/resources/Manual/Maths_Make_Ribbons.md
</details>

<details>
<summary>Page IDs for classes</summary>

|ID|Page
|:-|:-
|25116|content/classes/3.1/EngineCapabilities.md
|25117|content/classes/3.1/Engine.md
|25118|content/classes/3.1/Node.md
|25119|content/classes/3.1/Camera.md
|25120|content/classes/3.1/ArcRotateCamera.md
|25121|content/classes/3.1/AnaglyphArcRotateCamera.md
|25123|content/classes/3.1/StereoscopicArcRotateCamera.md
|25124|content/classes/3.1/TargetCamera.md
|25125|content/classes/3.1/FollowCamera.md
|25126|content/classes/3.1/FreeCamera.md
|25127|content/classes/3.1/AnaglyphFreeCamera.md
|25128|content/classes/3.1/DeviceOrientationCamera.md
|25129|content/classes/3.1/GamepadCamera.md
|25130|content/classes/3.1/AnaglyphGamepadCamera.md
|25132|content/classes/3.1/StereoscopicGamepadCamera.md
|25134|content/classes/3.1/StereoscopicFreeCamera.md
|25135|content/classes/3.1/TouchCamera.md
|25136|content/classes/3.1/VirtualJoysticksCamera.md
|25138|content/classes/3.1/VRDeviceOrientationFreeCamera.md
|25139|content/classes/3.1/WebVRFreeCamera.md
|25140|content/classes/3.1/Light.md
|25141|content/classes/3.1/DirectionalLight.md
|25142|content/classes/3.1/HemisphericLight.md
|25143|content/classes/3.1/PointLight.md
|25144|content/classes/3.1/SpotLight.md
|25145|content/classes/3.1/AbstractMesh.md
|25146|content/classes/3.1/InstancedMesh.md
|25147|content/classes/3.1/Mesh.md
|25148|content/classes/3.1/GroundMesh.md
|25149|content/classes/3.1/LinesMesh.md
|25150|content/classes/3.1/Scene.md
|25151|content/classes/3.1/Action.md
|25152|content/classes/3.1/SwitchBooleanAction.md
|25153|content/classes/3.1/SetStateAction.md
|25154|content/classes/3.1/SetValueAction.md
|25155|content/classes/3.1/IncrementValueAction.md
|25156|content/classes/3.1/PlayAnimationAction.md
|25157|content/classes/3.1/StopAnimationAction.md
|25158|content/classes/3.1/DoNothingAction.md
|25159|content/classes/3.1/CombineAction.md
|25160|content/classes/3.1/ExecuteCodeAction.md
|25161|content/classes/3.1/SetParentAction.md
|25162|content/classes/3.1/PlaySoundAction.md
|25163|content/classes/3.1/StopSoundAction.md
|25164|content/classes/3.1/InterpolateValueAction.md
|25165|content/classes/3.1/ActionEvent.md
|25166|content/classes/3.1/ActionManager.md
|25167|content/classes/3.1/Condition.md
|25168|content/classes/3.1/ValueCondition.md
|25169|content/classes/3.1/PredicateCondition.md
|25170|content/classes/3.1/StateCondition.md
|25171|content/classes/3.1/Animatable.md
|25172|content/classes/3.1/Animation.md
|25173|content/classes/3.1/EasingFunction.md
|25174|content/classes/3.1/CircleEase.md
|25175|content/classes/3.1/BackEase.md
|25176|content/classes/3.1/BounceEase.md
|25177|content/classes/3.1/CubicEase.md
|25178|content/classes/3.1/ElasticEase.md
|25179|content/classes/3.1/ExponentialEase.md
|25180|content/classes/3.1/PowerEase.md
|25181|content/classes/3.1/QuadraticEase.md
|25182|content/classes/3.1/QuarticEase.md
|25183|content/classes/3.1/QuinticEase.md
|25184|content/classes/3.1/SineEase.md
|25185|content/classes/3.1/BezierCurveEase.md
|25186|content/classes/3.1/Analyser.md
|25187|content/classes/3.1/AudioEngine.md
|25188|content/classes/3.1/Sound.md
|25189|content/classes/3.1/SoundTrack.md
|25190|content/classes/3.1/Bone.md
|25191|content/classes/3.1/Skeleton.md
|25192|content/classes/3.1/VRCameraMetrics.md
|25193|(D) content/classes/3.1/Collider.md
|25193|(D) content/classes/3.1/WorkerReplyType.md
|25193|(D) content/classes/3.1/WorkerTaskType.md
|25194|content/classes/3.1/CollisionCoordinatorWorker.md
|25195|content/classes/3.1/CollisionCoordinatorLegacy.md
|25196|content/classes/3.1/CollisionCache.md
|25197|content/classes/3.1/CollideWorker.md
|25198|content/classes/3.1/CollisionDetectorTransferable.md
|25199|content/classes/3.1/IntersectionInfo.md
|25200|content/classes/3.1/PickingInfo.md
|25201|content/classes/3.1/BoundingBox.md
|25202|content/classes/3.1/BoundingInfo.md
|25203|content/classes/3.1/BoundingSphere.md
|25204|content/classes/3.1/Octree.md
|25205|content/classes/3.1/OctreeBlock.md
|25206|content/classes/3.1/DebugLayer.md
|25207|content/classes/3.1/Layer.md
|25208|content/classes/3.1/LensFlare.md
|25209|content/classes/3.1/LensFlareSystem.md
|25210|content/classes/3.1/ShadowGenerator.md
|25211|content/classes/3.1/SceneLoader.md
|25212|content/classes/3.1/EffectFallbacks.md
|25213|content/classes/3.1/Effect.md
|25214|content/classes/3.1/Material.md
|25215|content/classes/3.1/MultiMaterial.md
|25216|content/classes/3.1/ShaderMaterial.md
|25217|content/classes/3.1/StandardMaterial.md
|25218|content/classes/3.1/FresnelParameters.md
|25219|content/classes/3.1/BaseTexture.md
|25220|content/classes/3.1/CubeTexture.md
|25221|content/classes/3.1/Texture.md
|25222|content/classes/3.1/DynamicTexture.md
|25223|content/classes/3.1/RawTexture.md
|25224|content/classes/3.1/RenderTargetTexture.md
|25225|content/classes/3.1/MirrorTexture.md
|25226|content/classes/3.1/VideoTexture.md
|25227|content/classes/3.1/ProceduralTexture.md
|25228|content/classes/3.1/CustomProceduralTexture.md
|25236|content/classes/3.1/Color3.md
|25237|content/classes/3.1/Color4.md
|25238|content/classes/3.1/Vector2.md
|25239|content/classes/3.1/Vector3.md
|25240|content/classes/3.1/Vector4.md
|25241|content/classes/3.1/Quaternion.md
|25242|content/classes/3.1/Matrix.md
|25243|content/classes/3.1/Plane.md
|25244|content/classes/3.1/Viewport.md
|25245|(D) content/classes/3.1/Frustum.md
|25245|(D) content/classes/3.1/Space.md
|25246|content/classes/3.1/Ray.md
|25247|content/classes/3.1/Axis.md
|25248|(D) content/classes/3.1/BezierCurve.md
|25248|(D) content/classes/3.1/Orientation.md
|25249|content/classes/3.1/Angle.md
|25250|content/classes/3.1/Arc2.md
|25251|content/classes/3.1/PathCursor.md
|25252|content/classes/3.1/Path2.md
|25253|content/classes/3.1/Path3D.md
|25254|content/classes/3.1/Curve3.md
|25255|content/classes/3.1/PositionNormalVertex.md
|25256|content/classes/3.1/PositionNormalTextureVertex.md
|25257|content/classes/3.1/SIMDHelper.md
|25258|content/classes/3.1/CSG.md
|25259|content/classes/3.1/Geometry.md
|25261|content/classes/3.1/VertexData.md
|25262|content/classes/3.1/SimplificationSettings.md
|25263|(D) content/classes/3.1/SimplificationQueue.md
|25263|(D) content/classes/3.1/SimplificationType.md
|25264|content/classes/3.1/DecimationTriangle.md
|25265|content/classes/3.1/DecimationVertex.md
|25266|content/classes/3.1/QuadraticMatrix.md
|25267|content/classes/3.1/Reference.md
|25268|content/classes/3.1/QuadraticErrorSimplification.md
|25269|content/classes/3.1/Polygon.md
|25270|content/classes/3.1/PolygonMeshBuilder.md
|25271|content/classes/3.1/SubMesh.md
|25272|content/classes/3.1/VertexBuffer.md
|25273|content/classes/3.1/Particle.md
|25274|content/classes/3.1/ParticleSystem.md
|25275|content/classes/3.1/PhysicsEngine.md
|25276|content/classes/3.1/CannonJSPlugin.md
|25277|content/classes/3.1/OimoJSPlugin.md
|25278|content/classes/3.1/PostProcess.md
|25279|content/classes/3.1/AnaglyphPostProcess.md
|25280|content/classes/3.1/BlackAndWhitePostProcess.md
|25281|content/classes/3.1/BlurPostProcess.md
|25282|content/classes/3.1/ColorCorrectionPostProcess.md
|25283|content/classes/3.1/ConvolutionPostProcess.md
|25284|content/classes/3.1/DisplayPassPostProcess.md
|25285|content/classes/3.1/FilterPostProcess.md
|25286|content/classes/3.1/FxaaPostProcess.md
|25287|content/classes/3.1/PassPostProcess.md
|25288|content/classes/3.1/RefractionPostProcess.md
|25290|(D) content/classes/3.1/StereoscopicInterlacePostProcess.md
|25290|(D) content/classes/3.1/TonemappingOperator.md
|25291|content/classes/3.1/VolumetricLightScatteringPostProcess.md
|25292|content/classes/3.1/VRDistortionCorrectionPostProcess.md
|25293|content/classes/3.1/PostProcessManager.md
|25294|content/classes/3.1/PostProcessRenderEffect.md
|25295|content/classes/3.1/PostProcessRenderPass.md
|25296|content/classes/3.1/PostProcessRenderPipeline.md
|25297|content/classes/3.1/LensRenderingPipeline.md
|25298|content/classes/3.1/SSAORenderingPipeline.md
|25299|content/classes/3.1/PostProcessRenderPipelineManager.md
|25300|content/classes/3.1/BoundingBoxRenderer.md
|25301|content/classes/3.1/DepthRenderer.md
|25302|content/classes/3.1/OutlineRenderer.md
|25303|content/classes/3.1/RenderingGroup.md
|25304|content/classes/3.1/RenderingManager.md
|25305|content/classes/3.1/Sprite.md
|25306|content/classes/3.1/SpriteManager.md
|25307|content/classes/3.1/MeshAssetTask.md
|25308|content/classes/3.1/TextFileAssetTask.md
|25309|content/classes/3.1/BinaryFileAssetTask.md
|25310|content/classes/3.1/ImageAssetTask.md
|25311|content/classes/3.1/TextureAssetTask.md
|25312|content/classes/3.1/AssetsManager.md
|25313|content/classes/3.1/Database.md
|25314|content/classes/3.1/FilesInput.md
|25315|content/classes/3.0/Gamepads.md
|25316|content/classes/3.1/StickValues.md
|25317|content/classes/3.1/Gamepad.md
|25318|content/classes/3.1/GenericPad.md
|25319|content/classes/3.1/Xbox360Pad.md
|25320|content/classes/3.1/SceneOptimization.md
|25321|content/classes/3.1/TextureOptimization.md
|25322|content/classes/3.1/HardwareScalingOptimization.md
|25323|content/classes/3.1/ShadowsOptimization.md
|25324|content/classes/3.1/PostProcessesOptimization.md
|25325|content/classes/3.1/LensFlaresOptimization.md
|25326|content/classes/3.1/ParticlesOptimization.md
|25327|content/classes/3.1/RenderTargetsOptimization.md
|25328|content/classes/3.1/MergeMeshesOptimization.md
|25329|content/classes/3.1/SceneOptimizerOptions.md
|25330|content/classes/3.1/SceneOptimizer.md
|25331|content/classes/3.1/SceneSerializer.md
|25332|content/classes/3.1/SmartArray.md
|25334|content/classes/3.1/Tags.md
|25335|content/classes/3.1/Tools.md
|25336|(D) content/classes/3.1/AsyncLoop.md
|25336|(D) content/classes/3.1/JoystickAxis.md
|25337|content/classes/3.1/VirtualJoystick.md
|25347|content/classes/3.1/MeshLODLevel.md
|25348|content/classes/3.1/AndOrNotEvaluator.md
|25349|content/classes/3.1/DDSTools.md
|25350|content/classes/3.1/TGATools.md
</details>

**Comment by deltakosh** [comment]
Please do:)

**Comment by mootari** [comment]
Can we also get rid of anything that handles forwarding from the old `/page.php?p=123` style URLs?

**Comment by deltakosh** [comment]
Yes:)

**Comment by mootari** [comment]
Additional files for removal:
- scripts/create-forward.js
- scripts/create-list-pages.js
- scripts/import-md-from-azure.js

**Comment by mootari** [comment]
Forwarder code for /page.php style URLs cannot yet be removed. There are dozens of page.php links in the current docs.

**Comment by deltakosh** [comment]
Perhaps we can just auto update .md content once and for all

**Comment by mootari** [comment]
I'm creating a manual list of redirects right now.

**Comment by mootari** [comment]
|ID|Page
|-|-
|21911|content/babylon101/babylon101/First.md
|22081|content/babylon101/babylon101/Animations.md
|22531|content/How_To/events/How_to_use_Actions.md
|22581|content/How_To/scene/How_to_use_SceneOptimizer.md
|22591|content/How_To/mesh/How_to_use_LOD.md
|22601|content/How_To/material/How_to_use_Procedural_Textures.md
|22611|content/tutorials/03_Advanced/Using_the_Debug_Layer.md (**missing**)
|24822|content/How_To/mesh/In-Browser_Mesh_Simplification.md
|24824|content/How_To/audio/Playing_sounds_and_music.md
|24825|content/How_To/material/How_to_use_DepthRenderer_to_get_depth_values.md
|24827|content/How_To/Videos/3D_on_the_Web_Understanding_the_Basics.md
|24828|content/How_To/Videos/WebGL_Basics.md
|24829|content/How_To/Videos/Using_Babylon.js_for_Beginners.md
|24830|content/How_To/Videos/Understanding_Materials_and_Inputs.md
|24831|content/How_To/Videos/Game_Pipeline_Integration_with_Babylon.js.md
|24832|content/How_To/Videos/Loading_Assets.md
|24833|content/How_To/Videos/Babylon.js_Advanced_Features.md
|24834|content/How_To/Videos/Special_Effects.md
|24837|content/How_To/Post_Process/Using_the_SSAO_rendering_pipeline.md
|24840|content/How_To/light/Using_the_Volumetric_LightScattering_post-process.md
|24841|content/How_To/Post_Process/Using_depth-of-field_and_other_lens_effects.md
|24847|content/babylon101/babylon101/Parametric_Shapes.md
|25088|content/How_To/mesh/Ribbon_Tutorial.md
|25090|content/How_To/mesh/How_to_use_Path3D.md
|25091|content/How_To/mesh/How_to_use_Curve3.md
|25094|content/How_To/mesh/Decals.md
|25096|content/How_To/mesh/How_to_dynamically_morph_a_mesh.md
|25109|content/How_To/Importer/STL.md

**Comment by mootari** [comment]
There's no redirect for the missing `content/tutorials/03_Advanced/Using_the_Debug_Layer.md` - what would be the closest equivalent?

**Comment by mootari** [comment]
That can't be good: forwarding of php.php redirects doesn't work at all at the moment, e.g. http://doc.babylonjs.com/page.php?p=24828

**Comment by mootari** [comment]
Some more duplicates:
- 22011:
  - content/babylon101/babylon101/Discover_Basic_Elements.md
  - content/How_To/mesh/Set_Shapes.md
- 22151:
  - content/babylon101/babylon101/Raycasts.md
  - content/babylon101/babylon101/Shadows.md

Also, should we redirect class pages to 3.0 or 3.1 if the ID is present for both? I assume 3.1?

**Comment by mootari** [comment]
Duplicate IDs for classes:
- 25245:
  - Frustum
  - Space
- 25193:
  - Collider
  - WorkerReplyType
  - WorkerTaskType
- 25248:
  - BezierCurve
  - Orientation
- 25263:
  - SimplificationQueue
  - SimplificationType
- 25290:
  - StereoscopicInterlacePostProcess
  - TonemappingOperator
- 25336:
  - AsyncLoop
  - JoystickAxis

**Comment by mootari** [comment]
@deltakosh I need you to go through the above duplicates and tell me which one to pick for each case, so that I can compile the final list of redirects.

**Edit:** You'll probably want to pick the ones that came first.

**Comment by BabylonJSGuide** [comment]
There's no redirect for the missing content/tutorials/03_Advanced/Using_the_Debug_Layer.md - what would be the closest equivalent?

content/features/PGsupport/Playground_debuglayer.md

**Comment by mootari** [comment]
> content/features/PGsupport/Playground_debuglayer.md

Thanks, added!

**Comment by mootari** [comment]
@deltakosh I still need feedback on those duplicate IDs in my earlier comments. They were likely copied over when someone added new markdown files and used old ones for reference.

**Comment by deltakosh** [comment]
You can remove all of them. I'll fix the redirect manually later on

**Comment by mootari** [comment]
I just noticed that Netlify only offers static hosting. Does that mean that we can rip out anything related to express?

**Comment by deltakosh** [comment]
This is correct. Only local JS code

**Comment by deltakosh** [comment]
Done
