### ISSUE TITLE
Remove external and temporary content

### ISSUE THREAD

**Issue by mootari** [BabylonJS/OldDocumentationSite#715]
Several files have been copied over from https://github.com/BabylonJS/Babylon.js or are only required during the build process. As a result these are often differ from the original source.

I propose to remove these from the Documentation repo and pull them in (or generate them) on demand. Benefits:
- Forces documentation errors to be fixed in the actual source first.
- Reduces size of shallow clones.
- Makes separation between authored and generated content clearer.
- Presumably makes updating affected content less involved.

Affected files:
- [ ] what's new:
  - path: `/content/whats-new/whats-new.md``
  - original source: https://github.com/BabylonJS/Babylon.js/blob/v3.0.7/what's%20new.md
  - additional notes:
    - Prefixed by page header (heading "Changes list", version number "3.0.0")
    - Heading levels need to be increased by two
- [ ] Type definitions:
  - path: `typedoc/babylon.*.d.ts`
  - original sources:
    - https://github.com/BabylonJS/Babylon.js/blob/master/playground/Babylon.d.txt

**Comment by deltakosh** [comment]
So you would prefer moving them manually to documentation repo? I don't see it as an improvement:)

**Comment by mootari** [comment]
> So you would prefer moving them manually to documentation repo? I don't see it as an improvement:)

On the contrary. Pull them automatically in during the build.

**Comment by deltakosh** [comment]
Wonderful;) you are a savior man!!
