### ISSUE TITLE
Create  good starter kit for BabylonJS with Modules, NPM and Webpack

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#720]

**Comment by brian-hay** [comment]
+1 on this. I suggested something along these lines here https://github.com/BabylonJS/Documentation/issues/887#issuecomment-375836337

**Comment by deltakosh** [comment]
I see this as doc page and not actual code in the repo

**Comment by deltakosh** [comment]
This is kind of done no? @RaananW

**Comment by RaananW** [comment]
yes! I have a few corrections, but it can be closed

**Comment by RaananW** [comment]
http://doc.babylonjs.com/features/npm_support
