### ISSUE TITLE
Documentation for AnimationGroup

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#726]
PG here: https://www.babylonjs-playground.com/#CBGEQX#1 

Need also to mention that AG can:
- update speedRatio 
- notify onAnimationEndObservable

Code: https://github.com/BabylonJS/Babylon.js/blob/master/src/Animations/babylon.animationGroup.ts

Thanks a lot!

**Comment by BabylonJSGuide** [comment]
Added today

**Comment by deltakosh** [comment]
Much appreciated
