### ISSUE TITLE
GettingStarted Page: Babylon Links switches between example code snippets

### ISSUE THREAD

**Issue by jppresents** [BabylonJS/OldDocumentationSite#748]
It starts with:

    
    <script src="https://cdn.babylonjs.com/babylon.js"></script>

but in the full html file it switches to (after eel free to copy-paste the following code in your index.html file):
  
    
    <script src="babylon.2.3.debug.js"></script>

Link: http://doc.babylonjs.com/#getting-started

**Comment by BabylonJSGuide** [comment]
Thank you for spotting and starting an issue
