### ISSUE TITLE
Prevent browser autocompletion from other sites bleeding into search field

### ISSUE THREAD

**Issue by mootari** [BabylonJS/OldDocumentationSite#750]
The search field currently uses the name `q` which is also used by hundreds of other sites.
This causes browsers (especially Chrome) to provide suggestions which will lead to zero results on doc.babylonjs.com:
<img width="282" src="https://user-images.githubusercontent.com/322014/34654439-c8a3e246-f3fb-11e7-85d7-4b1f4ac0bbca.png">

I strongly recommend to use a different name, e.g. `bjsq`, to limit conflicts with other sites and ensure that the suggestions only show terms the user has already entered before in this field.

Turning off autocompletion is impossible at the moment because Chrome ignores the attribute values `off` as well as custom invalid values that would normally disable autocompletion.

**Comment by deltakosh** [comment]
Please rename it:)
That looks like an easy fix:)

**Comment by mootari** [comment]
Would you also be open to exploring alternative search backends, like lunrjs (precompiled index with client side execution)? My hope is that this will allow us to improve the overall search experience by a large margin.

**Comment by deltakosh** [comment]
Open to everything. So far the index search cost me money so yes:)

**Comment by ssaket** [comment]
@deltakosh - Please review my pull request
