### ISSUE TITLE
Bad link in how_to_use_actions page

### ISSUE THREAD

**Issue by G-Rath** [BabylonJS/OldDocumentationSite#753]
Under the '[Sprites](https://github.com/BabylonJS/Documentation/blob/master/content/How_To/events/How_to_use_Actions.md#sprites)' header:

> Starting with Babylon.js 2.3, sprites can have an action manager: http://www.babylonjs...nd.com/#9RUHH#5

`http://www.babylonjs...nd.com/#9RUHH#5` is an invalid link.

Slightly related question: is there any documentation for the parameters of actions? (as in `{ trigger: BABYLON.ActionManager.OnKeyUpTrigger, parameter: "r" }`)

**Comment by deltakosh** [comment]
Thank you for reporting this issue!
It should be fixed now

We are in the process of enforcing comments for all functions but so far we do not have it yet :)

feel free to ask here about specific parameters in the meantime

**Comment by G-Rath** [comment]
@deltakosh When I say parameters, I don't mean for functions; I'm referring to the "parameters" property of actions.

Take this example from the same page:

```
scene.actionManager.registerAction(new BABYLON.ExecuteCodeAction(BABYLON.ActionManager.OnKeyUpTrigger, function (evt) {
   if (evt.sourceEvent.key == "r") {
       ...
   }
}));
scene.actionManager.registerAction(new BABYLON.ExecuteCodeAction({ trigger: BABYLON.ActionManager.OnKeyUpTrigger, parameter: "r" },
  function () {
            ...
}));
```

From that it seems that for `OnKeyUpTrigger` the parameter property is expected to be a string that is compared to the `evt.sourceEvent.key` property.

Then there's this example:

> For intersection triggers, you have to specify the "other" mesh with the following code:
> ```
> mesh.actionManager.registerAction(new BABYLON.SetValueAction({ trigger: BABYLON.ActionManager.OnIntersectionEnterTrigger, parameter: otherMesh }, mesh, "scaling", new BABYLON.Vector3(1.2, 1.2, 1.2)));
> ```
> You can as well define if you want to use precise intersections:
> ```
> mesh.actionManager.registerAction(new BABYLON.SetValueAction({ trigger: BABYLON.ActionManager.OnIntersectionEnterTrigger, parameter: { mesh:otherMesh, usePreciseIntersection: true} }, mesh, "scaling", new BABYLON.Vector3(1.2, 1.2, 1.2)));
> ```

In the first code example, parameter apparently can be a mesh, but can also be an object that has a property `mesh`, and a boolean property `usePreciseIntersection`

Finally, in https://github.com/BabylonJS/Babylon.js/issues/213 you said 'Next version will add a parameter to executecodeaction that will be the source object'; what's the naming of that property?

I'm finding it a bit confusing since I can't track down any definitive documentation on what 'parameters' specific ActionManager actions take.

This all stems from my trying to setup mouse events to handle a user mousing over meshes in a scene.
I'm trying to attach `OnPointerOverTrigger` & `OnPointerOutTrigger` `ExecuteCodeAction`s on the scene, but it never actually seems to work.

**Comment by deltakosh** [comment]
All trigger comes with an actionEvent which is defined here:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Actions/babylon.actionManager.ts#L6

You can see that the sourceEvent is something coming from the browser itself.

So in this case:
```
scene.actionManager.registerAction(new BABYLON.ExecuteCodeAction(BABYLON.ActionManager.OnKeyUpTrigger, function (evt) {
   if (evt.sourceEvent.key == "r") {
       ...
   }
}));
```
the sourceEvent is a DOM key event (and not a Babylon object).

The only specific parameter you can get from a trigger is the one you mentioned (which is defined in the doc :). Perhaps it is unclear obviously and I'm willing to improve the doc if this is the case)

Can you provide a repro of your attempt to use OnpointerOver?
(See a working example here: https://www.babylonjs-playground.com/#10CNYO#6)

**Comment by G-Rath** [comment]
Based on what I can find in the code, it seems like the only triggers that support specific parameters are the key triggers, and the intersection triggers. 

To me neither are *specifically* defined; they're used in examples, and so to me represent one possible parameter. But from my interpretation of your comment, it is meant to be treated as a specific definition. i.e. an example of the new property being introduce in https://github.com/BabylonJS/Babylon.js/issues/213 will be added to this page, thus making it 'defined'.

Personally I'm more a fan of specific documentation on such matters, say with a seperate section, or a nice table or list. But that's how I am - I'm still trying to get use to a lot of the quirks of Babylon, and it's documentation, so thank you for helping me with that. 

As for my  `OnPointerOver` issue, it's working fine with meshes, just not with scene. I thought that those actions on the scene would be triggered by mousing over any mesh in the scene, but that's not the case.

The way forward seems to be to just attach the required event to each and every mesh as they're 'created'.

https://www.babylonjs-playground.com/#XA4RUK

**Comment by deltakosh** [comment]
It is not an easy task to write good documentation. Would you mind trying to update the page to something that could look clearer to you? This could be invaluable help for us

Also you mention "quirks", can you give a list so we can try to improve?

regarding OnPointerOver (as stated in the [doc](http://doc.babylonjs.com/how_to/how_to_use_actions#triggers)), it is a mesh only action so you cannot add it to the scene

**Comment by G-Rath** [comment]
@deltakosh I have a bit of a love/hate relationship with documentation writing, so I can sympathise.

Heres an example of how I might do the page: https://gist.github.com/G-Rath/2e80f878fd4e1f8a89c5f15905912f5d

It looks a little squished because of gist's max-width.
I'd suggest moving to ES6, such as using arrow functions. 
I'd also look to use tables, but I couldn't be bothered right now :P

I also have no idea about `BABYLON.PredicateCondition`. I'd really like an example of how to use that. 

I'll give it a whack when I get some time (hopefully this weekend).

One documentation quirk off the top of my head is that I'm use to having a nice easy-to-read list of the members and properties of a class; for me a dropdown doesn't have the same effect. 

An engine quirk is that's currently on my mind is that meshes are added to the scene when instanced.
I'm coming from Pixi.js, where you'd create a `DisplayObject`, and then call `stage.addChild`.

I did miss the part about it OnPointerOver being mesh-only.  That one's on me :)
  
Right now my brains drained from work, but I'm more than happy to contribute what I can; Tho I don't want to step on anyone's toes.

**Comment by deltakosh** [comment]
This is really good! Please send a PR :) I will gladly merge it

We cannot use ES6 arrow functions though because we want to support all browsers (including ie11 or mobile browsers)

I'm not also satisfied by our dropdown and we need to spend time to revisit documentation UI (but we also need to add more doc, it is an infinite process...)

Our philosophy is to make sure people do more with less code. For instance most of the time you want your meshes to be in the scene so by default they are added in the scene. You can then remove them but our main goal is to reduce repetitive tasks like this one. So I won't call that a quick but a philosophical difference :D

For `PredicateCondition`:
```
var pointerOffCon = new BABYLON.PredicateCondition(shelves[i].actionManager, function () {
    return shelfMat.alpha.equals(0.2);
});
```
The condition will be true when predicate function will return true. It is jsut a callback called by the condition which delegate the control over condition completion to the user

By the way, I would advise to use our great Playground search feature when you want sample. This is what I did here for instance:
http://doc.babylonjs.com/playground?code=PredicateCondition

**Comment by G-Rath** [comment]
> We cannot use ES6 arrow functions though because we want to support all browsers (including ie11 or mobile browsers)

I had a feeling that would be the case :'(

Personally I'm for using basic ES6 features such as template string literals and arrow functions, as to encourage movement away from legacy browsers like IE11 (which is the only mainstream browser that doesn't support those two features, unless you count Opera Mini), and compilers like Babel can be used to bridge the compatibility gap. For now I'm happy to stick with the current format :)

I've updated my gist to include the PredicateCondition. It surprised me a little, as I've never actually heard of the mathmatical predicate until now (only knew about the gramatical version), but [it's a thing](https://en.wikipedia.org/wiki/Predicate_(mathematical_logic)).

I'll make a PR for that in an hour or so; I might have a play around with tables to see if I can make things look even better.

I'll have a look at the rest of the documentation, and see what else I can do.
If you've got a list of anything specific improvements, or anything you'd specifically like documented, feel free to chuck it my way and I'll do what I can :)

Also: thanks for clarifying about the mesh thing; that'll help me in the future to think 'in Babylon' :)

**Comment by deltakosh** [comment]
Thanks a lot for your appreciated help:) 
You can check all open issues we have here in this repo
