### ISSUE TITLE
features/position,_rotation,_scaling has incorrect links

### ISSUE THREAD

**Issue by G-Rath** [BabylonJS/OldDocumentationSite#756]
https://doc.babylonjs.com/features/position,_rotation,_scaling
https://github.com/BabylonJS/Documentation/blob/master/content/features/component/Position,_Rotation,_Scaling.md

> All of which depend on you knowing which frame of reference, either the world axes or the local axes, is being used.

`frame of reference` links to `features/Frame_Of_Reference` ([which gives a 404](https://doc.babylonjs.com/features/Frame_Of_Reference)) when it should link to `resources/frame_of_reference`

**Comment by deltakosh** [comment]
Fixed! thanks for pointing it out!
