### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mootari** [BabylonJS/OldDocumentationSite#768]
This project is currently missing a license which essentially means that both source code and documentation texts have to be considered as all rights reserved.

Because this documentation has seen several homes and has been improved and extended by many people, adding a license now might be more difficult than just dropping in a file. Considerations:
- Which license would be appropriate? (BabylonJS uses the Apache License 2.0)
- Should there be a split license for the source code / build environment and the authored texts and tutorials (and images)?
- Who would be considered the original copyright holder? (I'd assume David Catuhe, but IANAL)
- Can the documentation (and build environment) be relicensed without explicit permission from past contributors? (Probably needs to be answered by an actual lawyer)

As a side note, package.json states "MIT" as license, **but:**
1. This is likely just a default that was hastily confirmed during npm init and never changed afterwards.
2. Afaik it doesn't qualify as an actual license. The entry is only there to make it easier for npm users to search packages by license.

**Comment by mootari** [comment]
Relevant: https://www.quora.com/If-I-make-a-project-with-the-MIT-license-do-contributors-own-the-code-that-they-commit

**Comment by deltakosh** [comment]
We can use apache2. I'll be the original author 
No split license

Thanks a lot for rising this
