### ISSUE TITLE
Trying to include a code sample in a document gets it turned into a link

### ISSUE THREAD

**Issue by DavidHGillen** [BabylonJS/OldDocumentationSite#777]
```
/**
 * Example
 *     dome = new BABYLON.VideoDome("dome", url, {}, scene);
 **/
```
will compile to the attached image
![image](https://user-images.githubusercontent.com/932765/35071076-c6a75196-fb9c-11e7-8781-0bc1fc6c76fb.png)
This still occurs for ` code blocks as well

**Comment by deltakosh** [comment]
This is a known issue as we do not support sample directly. I suggest using link to the Playground for instance

**Comment by deltakosh** [comment]
As a side note @mootari is working on a lot of improvements for the documentation site :)
