### ISSUE TITLE
Function parameters that take multiple types do not document correctly

### ISSUE THREAD

**Issue by DavidHGillen** [BabylonJS/OldDocumentationSite#778]
When parsing a block like this
```
        /**
         * Text
         * @param name -
         * @param urlsOrVideo This text gets interrupted
         * @param options -
         */
        constructor(name: string, urlsOrVideo: string[] | HTMLVideoElement, options: {}
```
The output is like the attached image
![image](https://user-images.githubusercontent.com/932765/35071793-3dd23fc2-fb9f-11e7-8e3d-28f7f1926b03.png)
Despite trying several different formatting styles in the comment it always generates an error

**Comment by deltakosh** [comment]
Fixed with typedoc
