### ISSUE TITLE
Plane v PlaneGeometry

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#787]
In the current documentation `class Plane` is described as `new Plane(id, scene, size, canBeRegenerated, mesh, side)' . When used in this way both the stable and latest versions of BJS produce an object containing NaNs. The usage seems to be new Plane(a, b, c, d) where a, b, c and d  form the equation of the plane ax + by + cz + d = 0

class PlaneGeometry appears to be new for BJS 3.2 and hence works in the latest version but gives a `not a constructor` error in the stable version. This does take the form `new PlaneGeometry(id, scene, size, canBeRegenerated, mesh, side)'.

Hopefully the descriptions of classes Plane and PlaneGeometry in the documentation will be sorted when class documentation is generated for 3.2.

Does the current documentation for class Plane need to be changed manually or will it wait for 3.2?

[https://www.babylonjs-playground.com/#FYFLAZ](https://www.babylonjs-playground.com/#FYFLAZ)

**Comment by deltakosh** [comment]
Actually PlaneGeometry is not new but it was undocumented. It is an geometry  only object used to load.babylonjs file.

So nothing to change:)

**Comment by BabylonJSGuide** [comment]
What about the difference between the documentation for `Plane` and its usage?
In the  documentation  - class Plane is shown as constructed by

 `new Plane(id, scene, size, canBeRegenerated, mesh, side)' . 

When used in this way both the stable and latest versions of BJS produce an object containing NaNs. The usage seems to be  

`Plane(a, b, c, d) where a, b, c and d form the equation of the plane ax + by + cz + d = 0`

**Comment by deltakosh** [comment]
Can you point me to the documentation you mention?

**Comment by BabylonJSGuide** [comment]
[http://doc.babylonjs.com/classes/3.1/plane](http://doc.babylonjs.com/classes/3.1/plane)

You can see in the console what happens if you use as given in the documentation
[https://www.babylonjs-playground.com/#FYFLAZ#1](https://www.babylonjs-playground.co/#FYFLAZ#1)

but everything OK if you use Plane(a, b, c, d)
[https://www.babylonjs-playground.com/#FYFLAZ#2](https://www.babylonjs-playground.com/#FYFLAZ#2)

which I think might come from CSG code
__________________________________________________________________________________________________________
The reason I thought PlaneGeometry was new was because of the difference between 
the stable version in the PG [https://www.babylonjs-playground.com/indexstable.html#FYFLAZ#3](https://www.babylonjs-playground.com/indexstable.html#FYFLAZ#3)

and the latestVersion in  the PG [https://www.babylonjs-playground.com/index.html#FYFLAZ#4](https://www.babylonjs-playground.com/index.html#FYFLAZ#4)

but this is a Babylon issue not a documentation issue and has been corrected.

**Comment by deltakosh** [comment]
Ok the http://doc.babylonjs.com/classes/3.1/plane is completely broken
Hopefully the new API generator will fix it

I keep this issue open to make sure to check it

**Comment by RaananW** [comment]
PlaneGeometry is technically Geometry.Plane.
It is not new, but doesn't exist with the same syntax in 3.1 . 3.2 will not have the Geometry module anymore, there are a few "new" classes that moved from there (such as BoxGeometry and SphereGeometry).
We actually had 2 Plane classes in different namespaces. The Plane class comes either from the math file or geometry. Starting 3.2, Plane is a math-only class.
About the different between stable and current - I understand where it is coming from, and removing the Geometry namespace is actually a breaking change, but those were internal classes that should not have been used outside of the framework itself. The same goes to the Internals namespace, which was removed. The Internal classes are now a part of the public API, thou starting with "_".

**Comment by deltakosh** [comment]
Oh yeah! Now I remember 
So everything should be fine in 3.2 regarding documentation
