### ISSUE TITLE
Review english for particles doc

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#855]
https://github.com/BabylonJS/Documentation/edit/master/content/babylon101/babylon101/Particles.md

I guess we need you to check the english here :) A lot of non native writers added stuff to this page :)

**Comment by BabylonJSGuide** [comment]
Having read the page through, on editing it is my intention to leave particle system creation, emitter type (ie box, sphere and cone) and animation particles in babylon 101 and move custom effects and GPU particles to a page in "How To". There will be links between the two pages. Is this OK with you?

**Comment by deltakosh** [comment]
You're the boss:) as long as they are referenced in the 101, this is perfect for me

**Comment by BabylonJSGuide** [comment]
Found a bug see BJS issue 3947

**Comment by BabylonJSGuide** [comment]
Am still doing this just doing a more extensive revision than envisaged - more explanation and more playgrounds. Should be done by middle of next week.

**Comment by deltakosh** [comment]
No rush:)

**Comment by sebavan** [comment]
Hello @BabylonJSGuide , would be amazing if you could review my bad english in the shadows update :-)

**Comment by BabylonJSGuide** [comment]
@sebavan  will check it out in a couple of days

**Comment by BabylonJSGuide** [comment]
have updated and submitted PR
