### ISSUE TITLE
Typescript getting started guide omissions & confusion

### ISSUE THREAD

**Issue by brian-hay** [BabylonJS/OldDocumentationSite#887]
See http://doc.babylonjs.com/

Issues:

- Refers to / requires _babylon.d.ts_ file but doesn't indicate where to get it
- Says "We will only code in the _index.html_ file to keep it as simple and concise as possible" but then proceeds to use multiple files e.g. _game.ts_, _game.js_ etc.

**Comment by deltakosh** [comment]
Good catch!

**Comment by brian-hay** [comment]
@deltakosh that was a quick reply! I should really do this myself - have been meaning to get in and contribute to English documentation ...

**Comment by deltakosh** [comment]
If you want please be my guest:)
https://github.com/BabylonJS/Documentation/blob/master/views/index.pug

**Comment by brian-hay** [comment]
Hi @deltakosh. As this is my first doc contribution and I'm a bit of a noob with some of the related tech, can I get your advice on this?

In the TS starter example the latest babylon.js version is linked from CDN but if we require the first-time user to download a specific version of babylon.d.ts from say the github repo then save and reference it locally in their ts files, then there's the chance of version mismatches right? It doesn't seem like good practice to recommend this method to first-timers.

If you don't think it'll be much of an issue, I can make the minimal changes required to the docs to reflect this. If you have a better suggestion, please let me know.

Eventually I think it'd be good to have a few BJS project starter repositories like:

- babylon-js-starter
- babylon-ts-starter
- babylon-js-node-starter
- babylon-ts-node-starter
- babylon-js-node-multiplayer-starter (client-server architecture)
- babylon-ts-node-multiplayer-starter (client-server architecture e.g. https://github.com/endel/babylonjs-multiplayer-boilerplate)

The last example (using [Colyseus](https://github.com/gamestdio/colyseus)) really helped me.

But this is for another discussion or github issue.

**Comment by deltakosh** [comment]
I try to avoid multiplying repo because then we need to maintain them :)
Regarding the question, you should just ask them to download from https://cdn.babylonjs.com/babylon.d.ts

**Comment by brian-hay** [comment]
Thanks for the CDN link. Will use that.

I wasn't suggesting duplicating the entire BJS repo as part of the starter repos. Just creating project boilerplates/skeletons for different use-cases and developer language preferences etc.

**Comment by deltakosh** [comment]
I got your point :)
perhaps we could just add a starters folder in this repo to ease maintenance.

**Comment by brian-hay** [comment]
Have submitted PR #889
