### ISSUE TITLE
Playground: Earcut is not defined

### ISSUE THREAD

**Issue by Abdelkrim** [BabylonJS/OldDocumentationSite#892]
1. Open http://www.babylonjs-playground.com/#4GBWI5#1
2. An error appears "Line 12:13 - Earcut is not defined"

1. How to circumvent the issue?
2. All other samples using Earcut on the playground fails to run

**Comment by BabylonJSGuide** [comment]
Works in stable version so until sorted switch to stable version in playground (selector top left)
https://www.babylonjs-playground.com/indexstable#4GBWI5#1

**Comment by Abdelkrim** [comment]
Indeed, the stable version works.

Thanks

**Comment by BabylonJSGuide** [comment]
Still not working in 3.2

**Comment by deltakosh** [comment]
Please open it in main repo as it is not doc related

**Comment by BabylonJSGuide** [comment]
Solved

**Comment by hiteshsahu** [comment]
Add Earcut as dependency in your index HTML

<script src="https://preview.babylonjs.com/earcut.min.js"></script>
