### ISSUE TITLE
Results of using search do not link correctly

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#905]
When you use the search box in documentation then
1. API documentation is OK. Links to result show http://doc.babylonjs.com/api/classes/............ and link correctly

2. Any other results do not work since they contain the word 'search as in http://doc.babylonjs.com/search/How_To/........   rather than http://doc.babylonjs.com/How_To/Animate...........

**Comment by deltakosh** [comment]
I'll take care of it
