### ISSUE TITLE
Links in API documentation that have Incorrect Redirects 

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#935]
The broken redirect links in the API documentation are in the file below. The links on the left redirect to a 404 or redirect to the wrong page of the documentation, corrected redirects on the right. Some of these links occur multiple times

[broken links.txt](https://github.com/BabylonJS/Documentation/files/1915433/broken.links.txt)

**Comment by deltakosh** [comment]
Thanks I'll make sure to update the redirects

**Comment by deltakosh** [comment]
Unfortunately this is not supported (because of the hash) by the redirection platform of netlify.com:(

**Comment by BabylonJSGuide** [comment]
Have updated the links in Babylon.js ref PR #4166 Babylon.js

**Comment by deltakosh** [comment]
Thanks a lot!
