### ISSUE TITLE
New examples tab

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/OldDocumentationSite#946]
- [x] Add a new examples tab
- [x] Add description + small image + link + doc link per sample. Links only display title +image by default but can be unfold to display desc and doc link
- [x] Sort per category (animations,meshes,materials,shadows,physics,etc..)
- [x] Filter by title
- [x] List will be static in the doc website (static html generated at doc build time based on a Json file)
- [x] Something like: https://threejs.org/examples/ but where all links directly open the associated PG in a iframe on the right (through playground.babylonjs.com/frame.html). On mobile, links will open a new browser tab instead of loading the pg in the iframe
- [ ] ~~Add a new pane in the playground to replace the sample picker and use the same json to provide a filterable list of curated pgs~~ Will tackle that in a different issue 

Json list:
- [x] create the list
- [x] move all feature demos from homepage
- [x] move all samples from pg (list on top right corner) and then remove the button
- [x] move all pgs from http://doc.babylonjs.com/resources/playgrounds (and then remove the page)
- [x] file will be editable through PR

Also on doc webpage:
- [x] Rename samples to snippets or tutorials (and update first item title). Pinging @BabylonJSGuide for thoughts
- [x] move babylonjs from top to footer
- [x] rename documentation to home

**Comment by deltakosh** [comment]
Add description + image + link per sample 
Sort per category
List will be static in the website and editable through PR

**Comment by deltakosh** [comment]
Pinging @Jaskar

**Comment by BabylonJSGuide** [comment]
If I have the right idea you want to add an Examples Tab under which there will be a number of PG examples including the feature demos and those from the Interesting Playgrounds page. Also rename the Samples Tab.

I think Tutorials is a bit grand as a rename for the Samples Tab so I would go for renaming Samples as Snippets and then rename the Snippets Filter as Utilities and  possibly rename the Gamelets filters as Tutorials (but still a bit grand for the contents) so probably leave this name until a better one is though of?

**Comment by deltakosh** [comment]
Sounds good to me!!

**Comment by deltakosh** [comment]
Adding some cleanup tasks:
- [x] Completely hide the scroll bar on the right
- [x] Make sure there is no stuttering when moving mouse over menus
- [x] Remove search icon as filtering is done while typing
- [x] Make sure filter is reset when clicking the cross in the filter text box
- [x] on mobile remove the iframe and open examples on a new tab
- [x] Hide category if no content (due to filter)
- [x] Make sure scrolling is smooth on mobiles
cc @Jaskar
