### ISSUE TITLE
the pr process described in the readme is false or incomplete

### ISSUE THREAD

**Issue by GrosSacASac** [BabylonJS/OldDocumentationSite#97]
error message:It seems you do not have permissions blabla

**Comment by RaananW** [comment]
Care to share a bit more information?

**Comment by GrosSacASac** [comment]
in your readme is written
1. Head to content folder. All markdowns files are located in this folder.
2. Edit markdown according to your need
3. Use `grunt build`
4. Pull request :)

however to do a pull request you have to fork the repo first. but a bit before is also written and it s confusing to do git clone https://github.com/BabylonJS/Documentation.git. this does clone, but not fork, so when you later edit that clone the push command doesn't have the permission (because I am not in the contributor list) And the PR command isn't there at all, because it s a copy not a fork.

The solution is to add as first steps:

-1. Fork the repo
0. clone the forked repo
1. Head to content folder. All markdowns files are located in this folder.
2. Edit markdown according to your need
3. Use `grunt build`
4. Pull request :)

**Comment by RaananW** [comment]
Point taken.
Let me see how we can update the README.md file with this information.

Nonetheless, seems like you understood it rather quick :smile: so you can now send PRs.

**Comment by Kimoen** [comment]
Readme updated. Thank you for your comment :)
