### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by GrosSacASac** [BabylonJS/OldDocumentationSite#98]
replace 

```
var rot = BABYLON.Vector.RotationFromAxis(axis1, axis2, axis3);
```

with

```
var rot = BABYLON.Vector3.RotationFromAxis(axis1, axis2, axis3);
```

in the file Documentation\content\tutorials\03_Advanced\How_Rotations_and_Translations_Work.md
I could not PR this , see other issue

**Comment by RaananW** [comment]
Commited
