### ISSUE TITLE
Base demo in VLS page is wrong

### ISSUE THREAD

**Issue by Vinc3r** [BabylonJS/OldDocumentationSite#989]
I don't know what the base demo is supposed to show, so I can't fix it myself, but I'm quite sure it's not the right demo which is linked.

- Base demo link is at the bottom of [this page](http://doc.babylonjs.com/how_to/using_the_volumetric_lightscattering_post-process#and-now-its-time-to-play)
- playground linked is this one: https://www.babylonjs-playground.com/?25 (no VLS at all, plus old url style)

**Comment by deltakosh** [comment]
Thanks I replaced it with https://www.babylonjs-playground.com/#AU5641
Thank you for your appreciated help!
