### ISSUE TITLE
typos in Babylon 101 doc

### ISSUE THREAD

**Issue by jouerose** [BabylonJS/OldDocumentationSite#995]
on this page  https://doc.babylonjs.com/babylon101/parametric_shapes
1) In the CreateLines options table, you may have meant  "useVertexAlpha" instead of "useVertexColor" ?
2) In the CreateDashedLines options table, you may have meant  "dashNb" instead of "dashBn" ?

**Comment by BabylonJSGuide** [comment]
Thank you for pointing these out PR submitted

**Comment by jouerose** [comment]
Hi, I may have found others: 
on https://doc.babylonjs.com/babylon101/materials
these two lines : 
var myMaterial.alpha = 0.5;
var myMaterial.diffuseTexture.hasAlpha = true;

I did not think i should have opened another issue ticket for them. let me know if it would have been better.

cheers

**Comment by BabylonJSGuide** [comment]
That's OK I though in future it is probably better to open a new issue rather than commenting in a closed issue. If issue is open then just add relevevant findings. I will sort these typos out.. Any new typos start a new issue.

**Comment by BabylonJSGuide** [comment]
Have updated
