### ISSUE TITLE
No redirect for depth buffer

### ISSUE THREAD

**Issue by BabylonJSGuide** [BabylonJS/OldDocumentationSite#996]
This link http://doc.babylonjs.com/tutorials/using_logarithmic_depth_buffer from http://www.html5gamedevs.com/topic/28756-suggestion-for-solving-this-z-testingz-fighting-problem/?do=findComment&comment=165379 does not redirect to http://doc.babylonjs.com/how_to/using_logarithmic_depth_buffer

**Comment by deltakosh** [comment]
Fixed
